db/migrations/20200924152927_fix_article_draft_relationship.js, src/connectors/articleService.ts, src/connectors/draftService.ts, src/connectors/queue/user.ts
* Add migration script to fix article-draft relationship [1]
* Delete unpublished instead of unlinked drafts on archive user
**[1]** copy the article without `draft_id` to draft:
Article | Draft | Remark
-- | -- | --
id | id |  
uuid | uuid | generated by `v4()`
author_id | author_id |  
upstream_id | upstream_id | leave it blank, will be dropped
title | title |  
slug |   |  
cover | cover |  
summary | summary |  
word_count |   |  
dash_hash |   |  
media_hash |   |  
content | content |  
state |   |  
public |   |  
live |   |  
created_at | created_at | set to `created_at` of article
updated_at | updated_at | set to `created_at` of article
draft_id |   |  
remark |   |  
sticky |   |  
language |   |  
  | archived | set to `false`
  | publish_state | set to `published`
  | tags | …
=> Fix article-draft relationship

schema.graphql, src/definitions/schema.d.ts, src/queries/system/search.ts, src/types/system.ts
Add `record` boolean to search input to determine if search key needs to be stored.
=> feat(search api): add `record` boolean to input

src/mutations/article/deleteArticlesTags.ts
=> fix(notice): add await for sending delete article tag notices to avoid duplicate insertion keys

schema.graphql, src/definitions/schema.d.ts, src/queries/article/assets.ts, src/types/article.ts, src/types/draft.ts
Check permission inside resolver instead of `@auth(mode: "${AUTH_MODE.oauth}")` since `@auth` now only supports scope starting with `viewer`, which means the root type of the resolver is `User` and `Article.assets` [can't match](https://github.com/thematters/matters-server/blob/develop/src/types/directives/auth.ts#L22).
=> fix(asset): permission checking inside resolver instead of using `@auth`

src/common/utils/cookie.ts
After investigation, we found this issue occurs with `SameSite=Strict` on mobile Safari.
refs: [[1]](https://bugzilla.mozilla.org/show_bug.cgi?id=1617158) [[2]](https://stackoverflow.com/questions/55937018/previously-set-samesite-strict-cookie-not-available-in-document-cookie-firefo)
=> fix(cookie): set SameSite=Lax for `__user_group` cookie

src/common/utils/makeContext.ts, src/connectors/atomService.ts, src/connectors/draftService.ts, src/connectors/index.ts, src/connectors/tagService.ts, src/definitions/index.d.ts, src/mutations/article/deleteTags.ts, src/mutations/article/mergeTags.ts, src/mutations/draft/deleteDraft.ts, src/routes/graphql.ts, src/types/__test__/utils.ts
- Inject `knex` instance into context
- Make a new service gathering reusable methods to replace old services
- Make query and update methods looks like Prisma like.
=> refactor(service): inject knex into context and make a lighter service

schema.graphql, src/common/enums/notification.ts, src/connectors/__test__/notificationService.test.ts, src/connectors/notificationService/index.ts, src/connectors/notificationService/notice.ts, src/definitions/notification.d.ts, src/definitions/schema.d.ts, src/mutations/comment/putComment.ts, src/queries/notice/index.ts, src/types/notice.ts
* remove `CircleNewDiscussion` notice; 
* add `circle_*_mentioned_you`, `circle_*_new_reply` DB notice types to distinguish from article comment since some components (daily summary email) rely on it;
=> Revise Circle Notices

schema.graphql, src/definitions/schema.d.ts, src/queries/comment/circle/discussionCount.ts, src/queries/comment/circle/discussionThreadCount.ts, src/queries/comment/index.ts, src/types/comment.ts
Since circle discussion are protected and `discussion.totalCount` returns `0` on public query, we add `discussionCount` and `discussionThreadCount` to fulfill the stats needs.
=> feat(circle): add `discussionCount` and `discussionThreadCount`

src/common/enums/payment.ts, src/connectors/paymentService.ts, src/connectors/stripe/index.ts, src/definitions/index.d.ts, src/mutations/circle/invite.ts, src/mutations/circle/subscribeCircle.ts, src/mutations/circle/unsubscribeCircle.ts, src/queries/circle/invitation/freePeriod.ts, src/routes/pay/stripe/circle.ts
In this PR, we add support for creating subscription and subscription items with `provider=matters`, which currently used by trial invitation.
**Notes:**
* Matters subscription items also count in the limitation that up to 20;
* `freePeriod` should be altered from month to day unit by the next deployment (June 1);
=> Matters as subscription provider

src/common/utils/cookie.ts
Chrome 91 may change the default behavior of cookie `SameSite`, we need to set it to `none` explicitly.
=> fix(cookie): set samesite to `none` if it's local request

.github/workflows/deploy.yml, .github/workflows/test.yml, docker/docker-compose.yml
from last good deployment
https://github.com/thematters/matters-server/runs/3756298109?check_suite_focus=true#step:2:225
the latest good image is `Digest: sha256:f7e30972e35a839ea8ce00c060412face29aa31624fd2dc87a5e696f99835a91`
it's werid can't find a tagged version from https://hub.docker.com/r/ipfs/go-ipfs/tags?page=1&ordering=last_updated
some latest tagged versions there are tested not working either; might be a major version change incompatibility
=> fix the ipfs/go-ipfs:latest not working

src/types/article.ts
> Only the author can access the Article.assets, it's for article edit mode currently
https://github.com/thematters/matters-web/pull/2260#discussion_r718376301
=> document assets is accessible to author only

src/common/utils/__test__/xss.test.ts, src/common/utils/xss.ts
after #2282 merged and deployed, now thematters/matters-web#2114 is parted fixed, only for cases like
'<pre class="ql-syntax" spellcheck="false">Pre1\n</pre><p>Para2</p><p>Para3</p>'
it's now showing correctly not wrapping any paragraphs,
but if the content includes more complex format, like
'<pre class="ql-syntax" spellcheck="false">Pre1\n</pre><p>Para2</p><p>Para3 <a href="...">link</a></p>'
thematters/matters-web#2114 is then still reproducing, the real reason is our server side is not always saving exactly same HTML generated from the editor, in this case Quill editor is appending `rel="noopener noreferrer"` to `a` tag, but `rel` attribute is stripped by the server (the `xss`); then at next time Editor initialization time, `ReactQuill` is loading this server saved HTML into Quill …
=> make sure a anchor tag be able to save rel attribute

.github/workflows/schema.yml, package.json
As title, M1 (arm) machine cannot install rover in local, move it CI since it's only used by CI.
=> fix(deps): move rover installation to CI

src/common/environment.ts
the beanstalk has an error when all EnvironmentVariables growing over 4096 bytes.
```
2021-11-11 20:27:18 UTC-0800 ERROR Service:AmazonCloudFormation, Message:Template format error: Parameter 'EnvironmentVariables' default value '[****]' length is greater than 4096.
```
=> change MATTERS_OPENSEA_API_KEY to known constant

.ebextensions/private-files.config, .platform/nginx/conf.d/00_client_max_body_size.conf, .platform/nginx/conf.d/01_increase_timeout.conf, docker/Dockerrun.aws.json.example
Fix the following:
- In new EB env, the `current` folder maybe absent during initialization, e.g. when `clone` an environment;
- In new EB env, `nginx.conf` in `.ebextension` does not work.
=> fix: avoid the scenario where current folder does not exist

src/common/utils/getViewer.ts
```console
2021-12-08 07:26:56 error: "Cannot read properties of undefined (reading 'split')"
2021-12-08 07:26:56 error: "Cannot read properties of undefined (reading 'split')"
2021-12-08 07:26:56 error: "Cannot read properties of undefined (reading 'split')"
2021-12-08 07:26:56 error: "Cannot read properties of undefined (reading 'split')"
2021-12-08 07:26:56 error: "Cannot read properties of undefined (reading 'split')"
```
=> error message: why ip undefined could run `.split`?

src/connectors/gcp/index.ts
it has triggered many good gmail registration requests flagged as bot, need logs to know why
=> fix(): skip recaptcha checking bot traffic

db/migrations/20220412080000_alter_draft_index.js
the major one is on `draft(article_id)`
mitigate #2501
=> create indexes for query performance

package-lock.json, package.json, src/connectors/tagService.ts
hot-release/4.1.1 
changed tags search results order:
1. categories of `exact match`, `partial match`, and `everything else`
2. within each category, sort by num_articles descending
=> hot-release/4.1.1 

schema.graphql, src/connectors/tagService.ts, src/definitions/schema.d.ts, src/queries/article/index.ts, src/queries/article/tag/numArticles.ts, src/queries/article/tag/numAuthors.ts, src/types/article.ts
* fallback to query the main DB directly if `numArticles` and `numAuthors` is not from the recommendation DB;
* make `numArticles` and `numAuthors` required;
=> feat(tag): add fallback query for numArticles and numAuthors

src/queries/article/index.ts
// when the Article is duck'ing from a Draft it has articleId,
// otherwise when articleId is undefined, it's a native Article, just use 'id'
this should resolve thematters/matters-web#2578 without need to change front-end
=> fix(article-id): for the case when not duck'ing a Draft to Article

src/connectors/baseService.ts, src/connectors/queue/publication.ts, src/connectors/systemService.ts, src/connectors/tagService.ts, src/mutations/article/editArticle.ts, src/mutations/draft/putDraft.ts, src/types/__test__/draft.test.ts
1. to allow select existing too-long name tag (>40 chars)
2. skip creating of too-long name tag (>40 chars)
resolve #2595
[discussion]( https://mattersnews.slack.com/archives/C88CK7Q7L/p1658283285063969?thread_ts=1658282716.534899&cid=C88CK7Q7L)
=> feat(tag): tag validation pattern for new tag naming rules

schema.graphql, src/common/enums/notification.ts, src/connectors/__test__/notificationService.test.ts, src/connectors/notificationService/index.ts, src/connectors/notificationService/mail/sendDailySummary.ts, src/connectors/notificationService/notice.ts, src/connectors/queue/emails.ts, src/connectors/queue/publication.ts, src/definitions/notification.d.ts, src/definitions/schema.d.ts, src/mutations/circle/putCircleArticles.ts, src/mutations/comment/putComment.ts, src/queries/notice/index.ts, src/types/notice.ts, src/types/user.ts
* merge all comment-related notices into `CircleNewBroadcastComments` and `CircleNewDiscussionComemnts` and which is bundleable with optional `comments`, `replies` and `mentions`;
* reenable `CircleNewArticle` and `CircleNewBroadcast` since they still fit with product's need;
* temp disable email circle notices;
=> feat(notice): merge circle comment notics into `CircleNewBroadcastComments` and `CircleNewDiscussionComemnts`

schema.graphql, src/connectors/tagService.ts, src/definitions/schema.d.ts, src/queries/article/tag/recommended.ts, src/types/system.ts
Get `random` index from front-end, draw the data from random index
=> feat(related-tags): add shuffle api to related tags

src/common/utils/notice.ts, src/mutations/comment/putComment.ts
* make circle_new_article actors optional;
* skip triggering `circle_*_mentioned_you` if it's a new level 1 broadcast;
=> fix: make `circle_new_article` actors optional

src/connectors/__test__/tagService.test.ts, src/connectors/queue/publication.ts, src/connectors/tagService.ts, src/mutations/article/editArticle.ts, src/mutations/draft/putDraft.ts, src/types/article.ts
call `normalizeTagInput(content)` instead of `stripAllPunct` pre-filter'ing
=> fix/tag-name: allow re-use old existing non-standard tag names

src/routes/graphql.ts
a [issue](https://github.com/apollographql/apollo-server/issues/5059) on how to use `transform` to mask nest inputs.
=> feat(gql): enable `sendVariableValues` for usage reporting

src/connectors/articleService.ts, src/connectors/queue/publication.ts
only append the `latestArticleDataHash` once only, to save from timeout
=> fix(ipns-publishing): change to re-use previous published lastDataHash

src/connectors/articleService.ts, src/connectors/tagService.ts, src/queries/article/collection.ts, src/queries/article/transactionsReceivedBy.ts
there are occasoinally some warning lines:
A valid integer must be provided to offset
add check `Number.isFinite(...)` should suffice
=> feat(knex-call): normalize all querybuilder.offset calls

src/connectors/likecoin/index.ts
Notice: The [`GET /like/info/like/amount`](https://api.docs.like.co/#28ca3081-69d6-4a8a-9815-d96717eab287) has a undocumented field `cosmosLIKE`, and it should be the correct value of liker's balance.
https://mattersnews.slack.com/archives/CC032ME07/p1665214073263229
=> fix(likecoin): use `/like/info/like/amount` to get liker's balance

src/connectors/__test__/payToByBlockchainQueue.test.ts, src/connectors/__test__/paymentService.test.ts, src/connectors/paymentService.ts, src/connectors/queue/payTo/payToByBlockchain.ts
- fix `findOrCreateTransactionByBlockchainTxHash`  to create correct `blockchain_transaction` data
- handle wrong `blockchain_transaction` data  in  repeat job
=> fix `blockchain_transaction` having unexpected data

db/migrations/20221212123646_alert_user_add_last_seen.js, src/connectors/__test__/userService.test.ts
within 1 migrate fault and before it reaches production, this migrate file can still be changed; replace closes #3031
=> fix(db-revert): fix last_seen to default null

src/connectors/articleService.ts
- keep original search key before normalized for exact match first;
- fix search totalCount result from original search method (es or meili);
for Search articles with new Search-Rework Algorithms #2972
=> feat(articles-search): use meilisearch #3028

.github/workflows/test.yml, db/migrations/20210604103456_fix_circle_subscription_billing_cycle_anchor.js, db/testSetup.js, knexfile.js
- allow database migration  scripts to be reuse by other repos
- simplify github action config
- remove dead code
=> ci: allow database migration  scripts to be reused by other repos

src/connectors/articleService.ts, src/connectors/tagService.ts
- tag V0 search call ES and fallback to DB ilike search
=> feat(pg-search-renames): columns renamed title_ts_rank & text_cd_rank

src/connectors/articleService.ts
- revert(fdd8c4be): remove title_like_rank
; feat(pg-search-by-score): tag & user full text search first order by score ; instead of exact matches first
; article search add title_like_rank [0,1]
; quick search skip all tsvector match
=> revert(fdd8c4be): remove title_like_rank

src/mutations/user/generateSigningMessage.ts
The latest metamask-extension [implementation](https://github.com/MetaMask/metamask-extension/pull/14438/files#diff-bc1a0ee9f48af11e3d6e254efa7d9b109b4dda9128745873d94f29d2603e98abR48) of [EIP-4361](https://eips.ethereum.org/EIPS/eip-4361#informal-message-template) may require *case-sensitive* matching domain. It is likely an inappropriate implementation, for the fact that [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.2.1) requires the host to be case-insensitive.
However, it has affected all users signing with MetaMask browser extension, showing phishing alert.
I have tested with Proxyman to show this solution should eliminate false phishing alert.
=> fix(wallet): sign in with Ethereum

src/mutations/user/generateSigningMessage.ts
use ${environment.siteDomain} to construct website link
=> feat(in-wallet): allow both .news & .town domain

src/routes/graphql.ts
We  use `graphql-upload` package to implement file-uploading, In this case apollographql advise to enable `csrfPrevention`  for safe,  see https://www.apollographql.com/docs/apollo-server/v3/data/file-uploads/
=> feat(csrf): enable ApolloServer `csrfPrevention`

package-lock.json, package.json
The client is still using the legacy editor which cannot parse new HTML attributes and tags correctly, e.g.
For video figure,
```html
<figure class="embed-video">...</figure>
<figure class="embed">...</figure>
<figure class="embed embed-video">...</figure>
```
For code figure,
```html
<figure class="embed-code">...</figure>
<figure class="embed">...</figure>
<figure class="embed embed-code">...</figure>
```
For audio figure,
```html
<figure class="audio" data-file-name="xxxx">...</figure>
<figure class="audio">...</figure>
<figure class="audio" data-file-name="xxxx">...</figure>
```
* https://github.com/thematters/matters-editor/pull/425/commits/441b15be44e7510da8d01f7f36e491ec8a552c7a
=> fix(editor): fix backward compatibility issue

package.json, src/index.ts
Helmet `crossOriginOpenerPolicy` was changed to enable by default at [5.0.0](https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#500---2022-01-02), which might break the LikeCoin OAuth flow
=> feat: disable helmet.crossOriginOpenerPolicy

src/connectors/likecoin/index.ts
to avoid resend jobs to lambda
=> fix(civicliker): cache fake civicliker longer 

src/connectors/likecoin/index.ts
likecoin chain upgrade v4.0.0 uses cosmos-sdk 0.46, which removed legacy `/txs` endpoint
the new txs endpoint is at `/cosmos/tx/v1beta1/txs` with slightly different formatting
sample tx:
https://mainnet-node.like.co/cosmos/tx/v1beta1/txs/014BB68CADC5B1F129E41D8CE6D5CA96236A2F04FE1FAF92D047EAC7B5C24625
=> fix: likecoin upgrade broke cosmos tx endpoint

src/connectors/__test__/articleService.test.ts, src/connectors/__test__/userService.test.ts, src/connectors/queue/payout.ts, src/connectors/userService.ts, src/mutations/circle/subscribeCircle.ts, src/mutations/user/addCredit.ts, src/mutations/user/payout.ts, src/mutations/user/setPassword.ts, src/routes/pay/stripe/index.ts
- check email if verified before set password
- correct `user.email` type to be `string | null` and pass build
=> feat: check email if verified before set password and fix typing

src/connectors/cloudflare/index.ts, src/mutations/system/directImageUpload.ts
resolves #249
Client side has 3 steps to call this API:
1. call `directImageUpload` to get an Asset with direct upload url;
2. post image as file to this direct upload url;
3. (async) post result url to directImageUpload, mark `draft` boolean to false;
=> feat(cfsvc): cloudflare direct image uploading: Implementation

.devcontainer/devcontainer.json, .devcontainer/library-scripts/docker-in-docker-debian.sh, .devcontainer/library-scripts/node-debian.sh, .devcontainer/setup-user.sh
The devcontainer config file was a bit outdated, and a lot of configuration/scripts have changed since then. I was unable to start a new dev container in vscode, so I forked over the latest scripts and updated the configurations so that it runs with the [0.309.0](https://github.com/microsoft/vscode-remote-release/issues/9060#issuecomment-1747811300) version of the devcontainer vscode extension.
Feel free to crosscheck the config files with the latest release 0.245.2 [here](https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/codespaces-linux/.devcontainer).
no related PRs
=> fix: dev container config file updates

src/common/enums/logging.ts, src/mutations/collection/addCollectionsArticles.ts, src/mutations/collection/deleteCollectionArticles.ts, src/mutations/collection/deleteCollections.ts, src/mutations/collection/putCollection.ts
Add audit logger for collection operations:
- Create collection
- Remove collection
- Add articles into a collection
- Remove articles from a collection
=> feat(collection-log): add audit logger for collection operations

src/common/errors.ts, src/common/utils/connections.ts, src/connectors/__test__/articleService.test.ts, src/connectors/articleService.ts, src/definitions/index.d.ts, src/mutations/comment/putComment.ts, src/queries/response/article/responses.ts, src/types/__test__/2/comment.test.ts
- use `created_at` as cursor directly instead of `row_number`
- combine 2  db querying into one
- re https://github.com/thematters/matters-server/issues/3165
- refactor
=> feat(responses):  filter comments in backend

docker/Dockerfile
add python3 for building opencc; it might be builtin in `node:16` image but `node:18` image needs it explicitly
resolves #3622
=> feat(node-v18): Bump deps: Node.js 18.x

src/connectors/articleService.ts, src/connectors/atomService.ts, src/mutations/article/editArticle.ts
dataloader return same objects in memory for same identifiers:
```javascript
const object =  await dataloader.load(1)   // object {id: 1,   content: 'test'}
delete object.id   // object now  {content: 'test'}
// code in other files
const object1 = await  dataloader.load(1)  // object1  {content: 'test'}
```
=> fix: avoid modifing object returned by dataloader

src/types/__test__/2/auth.test.ts, src/types/directives/auth.ts
(cherry picked from commit b8266792d9f940c0f34b26882067979942df2e5b)
=> [hotfix-master] fix(oss): fix to throw errors when visitor querying oss info

src/queries/article/relatedArticles.ts
objects returned by `findByAuthor` should contain `id`,  as inside the helper function `addRec`,  `_.uniqBy(..., 'id')` is called, passing objects w/o `id` field will filter and return only one object, which is the cause some articles' return only 1 related article.
=> fix(related-articles): fix relatedArticle resolver that return only 1 article in some case

src/queries/draft/article/drafts.ts, src/queries/draft/article/newestPublishedDraft.ts
matters-web 4.30.2 (prod) still relies on those APIs for article revision, but server does not create new drafts but article-versions, we temporarily fake the APIs to fix the problem
=> feat(draft): temporarily use article version as draft in article drafts API

src/connectors/__test__/atomService.test.ts, src/definitions/payment.d.ts, src/routes/pay/stripe/customer.ts
`cardLast4` is transformed to `card_last4` instead of `card_last_4`
=> fix(atomservice): work around knexSnakeCaseMappers edge case

db/migrations/20240429155918_migrate_article_versioning_data_3.js
The published states of those drafts are incorrect, so previous migrations have overlooked them.
=> fix(migration): migrate pending drafts of active articles to article_version and article_content

src/mutations/article/appreciateArticle.ts
likecoin doesn't allow self-like
=> fix(like): skip calling likecoin api when sender and author is same

schema.graphql, src/connectors/paymentService.ts, src/connectors/queue/__test__/payToByBlockchain.test.ts, src/connectors/queue/payTo/blockchain.ts, src/definitions/schema.d.ts, src/mutations/user/payTo.ts, src/types/__test__/2/payment.test.ts, src/types/payment.ts
* Revise `payTo` mutation and add `id` field to input;
1. User can call `payTo` with `txHash` as before to settle the tx;
2. Or user can make a draft (pending) tx w/o `txHash` first, then settle the tx later with transaction `id` and `txHash`;
* Revise `PayToByBlockchainQueue#_handleNewEvent` and support to correct tx that haven't been settled (as `#2` scenario);
resolve https://github.com/thematters/matters-server/issues/3859
=> feat(donation): add `PayToInput.id` to settle draft tx

src/common/utils/knex.ts, src/connectors/__test__/articleService.test.ts
`spam_score` takes effect only when `is_spam` is null
=> fix(spam-detection): fix excludeSpam where condition

src/common/utils/__test__/mention.test.ts, src/common/utils/mention.ts, src/queries/article/language.ts
https://github.com/thematters/matters-server/pull/4155
=> Strip @mention for article language resolver
