thematters/matters-server

schema.graphql
src/common/enums.ts
src/common/utils/notice.ts
src/connectors/__test__/notificationService.test.ts
src/connectors/notificationService/index.ts
src/connectors/notificationService/mail/index.ts
src/connectors/notificationService/mail/sendAdoptTag.ts
src/connectors/notificationService/mail/sendAssignAsTagEditor.ts
src/connectors/notificationService/mail/utils.ts
src/connectors/notificationService/notice.ts
src/connectors/tagService.ts
src/definitions/notification.d.ts
src/definitions/schema.d.ts
src/mutations/article/updateTagSetting.ts
src/queries/notice/index.ts
src/types/notice.ts

feat(notice): add API interface for tag management notice and email

---

db/migrations/20200731143200_correct_tag_creator.js
db/migrations/20200803101100_correct_tag_creator_pt_2.js

Comment unused console output, but keep for who wants to read codes. 🧑🏻‍💻

ci(migration): comment unused console output, but keep for reading

---

src/common/enums.ts
src/connectors/queue/migration.ts
src/connectors/queue/publication.ts
src/connectors/queue/user.ts
src/connectors/systemService.ts
src/mutations/article/putTag.ts
src/mutations/draft/putDraft.ts
src/mutations/oauthClient/putOAuthClient.ts
src/mutations/system/singleFileUpload.ts
src/mutations/user/updateUserInfo.ts
src/queries/draft/assets.ts

* Remove fallback and reset cover in `putDraft`
* Prevent deleting cover asset in `deleteUnusedAssets` 
https://github.com/thematters/matters-web/issues/1527

Custom Draft Cover

---

src/mutations/article/updateTagSetting.ts

feat(resolver): add auto-follow tag after being tag maintainer

---

src/mutations/article/addArticlesTags.ts
src/mutations/article/updateArticlesTags.ts
src/mutations/article/updateTagSetting.ts

feat(notice): add notice for tag management

---

schema.graphql
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/draft/putDraft.ts
src/queries/article/assets.ts
src/queries/article/index.ts
src/types/article.ts
src/types/draft.ts

* Add `Article.assets`; 
* Allow to edit `cover` for `editArticle` mutation;
* Rename `coverAssetId` of `PutDraftInput` to `cover` 
* Alter `Article.mediaHash` & `Article.dataHash` to `!`

Edit Article Cover

---

src/connectors/notificationService/mail/sendAdoptTag.ts
src/connectors/notificationService/mail/sendAssignAsTagEditor.ts
src/mutations/article/updateTagSetting.ts

fix(email): add tag id for tag management email

---

schema.graphql
src/common/enums.ts
src/connectors/queue/publication.ts
src/connectors/systemService.ts
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/draft/putDraft.ts
src/mutations/system/singleFileUpload.ts
src/types/article.ts
src/types/system.ts

* Add `cover` to `AssetType` for customized article/draft cover;
* Protect `Article.assets`;

Alter `AssetType` 

---

src/mutations/article/updateTagSetting.ts
src/queries/article/content.ts
src/queries/article/dataHash.ts
src/queries/article/index.ts
src/queries/article/language.ts
src/queries/article/mediaHash.ts
src/queries/article/slug.ts
src/queries/article/summary.ts
src/queries/article/title.ts
src/queries/article/wordCount.ts
src/types/__test__/system.test.ts

Update article query resolver due to draft and article data restructure

---

src/common/errors.ts
src/mutations/article/updateTagSetting.ts
src/types/__test__/tag.test.ts

fix(error): replace general errors of updating tag editors wit specific one

---

schema.graphql
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/queries/article/user/tags.ts
src/types/user.ts

feat(resolver): revise api to return tags that user own and maintain

---

db/migrations/20201021023701_update_article_hottest_a_criteria.js
db/migrations/20201021023707_update_article_hottest_b_criteria.js

Remove admin -> group b criteria

Update user grouping criteria for hottest article views

---

src/queries/article/createdAt.ts
src/queries/article/index.ts

fix(resolver): fix article is returning draft's created date

---

src/routes/oauth/index.ts
src/routes/oauth/stripeConnectHandler.ts

fix(oauth): add error catcher for viewer query in oauth server

---

db/migrations/20201103090135_recreate_curation_tag_materialized.js

feat(view): recreate curation tag materialized view

---

src/mutations/article/appreciateArticle.ts
src/mutations/article/readArticle.ts

Since `slug` field will be removed from `Article` table, fix it using slugify instead of getting from `Article` table.

fix(slug): fix getting wrong slug when recording read and super like

---

src/common/utils/index.ts

The max length of user name is 15, so shrink user name made by system. System will append a random number (1 ~ 999) to it if there is an identical one, so the change here is `12` not `15`.

fix(register): fix invalid user name made by system

---

src/connectors/articleService.ts

fix(search): fix article search returning nothing when pasting url

---

src/common/utils/cookie.ts

Reverts thematters/matters-server#1575 by https://github.com/thematters/matters-web/pull/1621

Revert "fix: fix the iOS browser cookie lost issue"

---

src/common/utils/content.ts
src/mutations/article/editArticle.ts
src/queries/article/content.ts
src/queries/draft/article/drafts.ts

After investigation, found out cheerio will convert iframe into self-closing tag during processing. More info, search self-closing tag in cheerio's Github repository.

fix(draft): fix self-closing tag exists in draft content

---

src/common/utils/content.ts
src/mutations/article/editArticle.ts
src/queries/article/content.ts
src/queries/draft/article/drafts.ts

cherry-pick from https://github.com/thematters/matters-server/pull/1624

[hotfix - master] fix(draft): fix self-closing tag exists in draft content

---

src/connectors/likecoin/index.ts
src/connectors/userService.ts
src/mutations/user/generateLikerId.ts

feat(likecoin connector): add ip info to likecoin requests

---

src/connectors/likecoin/index.ts
src/connectors/userService.ts
src/mutations/user/generateLikerId.ts

Master: feat(likecoin analytics): add ip info to likeco calls

---

db/migrations/20210112193112_add_unique_constraint.js
schema.graphql
src/connectors/atomService.ts
src/definitions/schema.d.ts
src/mutations/circle/index.ts
src/mutations/circle/putCircle.ts
src/mutations/circle/putCircleArticles.ts
src/mutations/circle/subscribeCircle.ts
src/mutations/circle/unsubscribeCircle.ts
src/types/circle.ts
src/types/comment.ts

* add `putCircleArticles` mutation;
* add `atomService.upsert`;

Add or remove articles from circle

---

src/connectors/likecoin/index.ts
src/connectors/userService.ts
src/mutations/user/generateLikerId.ts

Reverts thematters/matters-server#1708

Revert "Master: feat(likecoin analytics): add ip info to likeco calls"

---

db/migrations/20210113172906_add_circle_to_draft.js
db/migrations/20210113172906_add_circles_to_draft.js
schema.graphql
src/common/errors.ts
src/connectors/queue/publication.ts
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/circle/putCircle.ts
src/mutations/circle/putCircleArticles.ts
src/mutations/circle/subscribeCircle.ts
src/mutations/circle/toggleFollowCircle.ts
src/mutations/circle/unsubscribeCircle.ts
src/mutations/draft/putDraft.ts
src/queries/article/summary.ts
src/queries/draft/circle.ts
src/queries/draft/index.ts
src/schema.ts
src/types/article.ts
src/types/draft.ts

* Add support for adding a circle to draft and article;
* Add support for customizing summary of draft & article;
* Add `CIRCLE_NOT_FOUND` error;

Circle Draft

---

src/connectors/stripe/index.ts
src/queries/comment/circle/discussion.ts

fix(circle): disable proration on delete subscription item or cancel subscription

---

src/common/enums/payment.ts
src/common/utils/getLanguage.ts
src/common/utils/getViewer.ts
src/connectors/gcp/index.ts
src/connectors/notificationService/translations/index.ts

* support English in header parser
* support English in Google translation
* add English text to notification and error messages

[master] english support

---

src/connectors/atomService.ts

Same as https://github.com/thematters/matters-server/blob/develop/src/connectors/baseService.ts#L64

Fix incorrect order of dataloader

---

src/common/utils/validator.ts
src/connectors/paymentService.ts
src/mutations/comment/unvoteComment.ts
src/mutations/comment/voteComment.ts
src/queries/article/content.ts
src/queries/circle/isMember.ts
src/queries/comment/circle/discussion.ts

* Fix article content returns an empty string for circle member;
* Revise name validators;

fix(circle): return empty discussion for non-member

---

src/common/utils/time.ts
src/connectors/stripe/index.ts

fix(circle): fix `getUTC8NextMonday` wrong calculation when today is monday

---

src/connectors/paymentService.ts
src/mutations/circle/subscribeCircle.ts
src/mutations/circle/unsubscribeCircle.ts
src/routes/pay/stripe/circle.ts

* fix wrong queries of active subscriptions on (un)subscribe circle [1];
* fix missing notification and auto-follow on circle subscription if it's in sync;
[1] Same issue with https://github.com/thematters/matters-server/pull/1760

Bugfixes: Circle Subscription

---

schema.graphql
src/connectors/draftService.ts
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/circle/putCircleArticles.ts
src/queries/article/index.ts
src/queries/article/revisionCount.ts
src/queries/draft/assets.ts
src/queries/draft/content.ts
src/queries/draft/cover.ts
src/queries/draft/index.ts
src/types/article.ts
src/types/draft.ts

Also,
* add protection for `Draft.assets`, `Draft.content` and `Draft.cover`;

feat(circle): republish on putting article into paywall

---

package-lock.json
package.json

fix(matters-html-formatter): upgrade to fix ipfs size check issue

---

src/connectors/articleService.ts

fallback to index.html when no bundle path is returned from IPFS

fallback to index.html when no bundle path

---

src/connectors/articleService.ts

[Hotfix - master] fallback to index.html when no bundle path

---

.github/workflows/schema.yml
src/types/payment.ts

Also,
* remove `@constraint ` on `type` field since we use it only on `input` for now.

fix(ci): fix wrong ci syntax of schema push step

---

src/queries/comment/user/commentedArticles.ts

fix(comment): exclude inactive comments of `commentedArticles`

---

db/migrations/20210906101635_update_hottest_feed.js

- Lower the weight of Circle articles, i.e. `circle_boost`, from 6x to 2x.
- Set `donation_decay_factor` to 0.7 to weaken the donation boost efficiency of normal users.
- Add some new "Matty"

update hottest feed

---

db/migrations/20210906120153_create_topic_table.js
db/migrations/20210906120945_create_article_topic_table.js
db/migrations/20210906121322_create_chapter_table.js
db/migrations/20210906121514_create_article_chapter_table.js
package-lock.json
package.json
schema.graphql
src/definitions/schema.d.ts
src/types/article.ts
src/types/user.ts

* Topic & Chapter related GQL schema
* Topic & Chapter related DB schema

Personal page GQL & DB schema

---

schema.graphql
src/connectors/atomService.ts
src/definitions/schema.d.ts
src/queries/article/index.ts
src/queries/article/topic/latestArticle.ts
src/queries/article/user/topics.ts
src/queries/system/node.ts
src/types/__test__/user.test.ts
src/types/article.ts
src/types/user.ts

* Add `Topic.latestArticle`;
* Change `User.topics` to pagination;

Revise topic 

---

db/migrations/20210906101635_update_hottest_feed.js

- fix donation_decay_factor
- fix SQL

fix hottest SQL

---

db/migrations/20210917152820_fix_update_hottest_feed.js

- add new db migration to fix hottest feed

add fix db migration

---

.github/workflows/deploy.yml

still need another MATTERS_OPENSEA_API_KEY for prod deployment

for dev deployment

---

src/common/utils/getViewer.ts

https://github.com/thematters/matters-server/pull/2146

remove support for get token user via uuid

---

src/connectors/opensea/index.ts
tests/k6.js

use it like:
```
> time k6 run -e SERVER_HOSTNAME='server-develop.matters.news' ./tests/k6.js
running (11.0s), 00/10 VUs, 33 complete and 0 interrupted iterations
default ✓ [======================================] 00/10 VUs  10s
✓ status was 200
✓ body was application/json
✓ post status was 200
✓ post res body was application/json
✓ post query UserProfilePrivate res body was application/json
checks.........................: 100.00% ✓ 198      ✗ 0
data_received..................: 183 kB  17 kB/s
data_sent......................: 34 kB   3.1 kB/s
http_req_blocked...............: avg=98.27ms  min=0s       med=1µs      max=973.05ms p(90)=194.54ms p(95)=972.94ms
http_req_connecting............: avg=26.28ms  min=0s       med=0s       max=273.21ms p(90)=49.43ms  p(95)=257.09ms …
```

add k6 load test script, to test server endpoint capacity

---

package-lock.json
package.json
src/mutations/user/updateUserInfo.ts

this is triggering a test case failure at master merge, weird
https://github.com/thematters/matters-server/runs/4514437478?check_suite_focus=true#step:8:383

comment out console.log

---

package-lock.json
package.json
src/common/environment.ts
src/connectors/aws/index.ts
src/connectors/opensea/index.ts
src/mutations/user/updateUserInfo.ts
src/routes/img-cache/index.ts
src/types/user.ts
tests/k6.js

merge `master` back and remove some console.log lines 
also remove the non-effective `@cacheControl` on nfts
nfts: [NFTAsset!] @CacheControl(maxAge: ${CACHE_TTL.MEDIUM}, scope: PRIVATE)

merge master back and remove some console.log lines

---

src/mutations/article/editArticle.ts
src/mutations/circle/putCircleArticles.ts
src/mutations/draft/putDraft.ts
src/types/__test__/article.test.ts
src/types/__test__/draft.test.ts

remove ARR license checker, to allow ARR open to public

---

src/mutations/draft/putDraft.ts
src/types/__test__/draft.test.ts

resolves #2359 [Server] - Support ARR license for articles 3 pt feature request

fix/ license should remain unchanged after changing other fields

---

schema.graphql
src/common/enums/hardcode.ts
src/connectors/baseService.ts
src/connectors/tagService.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/mutations/user/changeEmail.ts
src/mutations/user/generateSigningMessage.ts
src/mutations/user/index.ts
src/mutations/user/userRegister.ts
src/mutations/user/walletLogin.ts
src/types/user.ts

feat/walletLogin - Revise APIs for wallet authentication

---

schema.graphql
src/common/utils/__test__/getViewer.test.ts
src/common/utils/getViewer.ts
src/connectors/__test__/systemService.test.ts
src/connectors/baseService.ts
src/connectors/userService.ts
src/definitions/index.d.ts
src/definitions/schema.d.ts
src/mutations/user/changeEmail.ts
src/mutations/user/walletLogin.ts
src/types/user.ts

drop using eth address, find the user from viewer.id instead
required by thematters/matters-web#2380

fix/change-email: change email in case when did not have email

---

package-lock.json
schema.graphql
src/connectors/tagService.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/mutations/user/changeEmail.ts
src/mutations/user/generateSigningMessage.ts
src/mutations/user/resetPassword.ts
src/mutations/user/updateUserInfo.ts
src/mutations/user/userRegister.ts
src/mutations/user/walletLogin.ts
src/queries/user/index.ts
src/queries/user/isWalletAuth.ts
src/queries/user/rootUser.ts
src/types/user.ts

* force wallet signup with email;
* revert changes on `changeEmail` mutation;
* add `User.info.isWalletAuth` for client to detect if disable reset password feature;
* add `ethAddress` argument to root `user` query for client to detect if current auth is login or sign up;

feat(wallet): force wallet signup with email

---

src/queries/circle/invites/accepted.ts
src/queries/comment/user/commentedArticles.ts

use knex builtin `.clone` instead of lodash/clone

---

package-lock.json
package.json
src/queries/circle/invites/accepted.ts
src/queries/comment/user/commentedArticles.ts

[hotfix - master] use knex builtin `.clone` instead of lodash/clone

---

src/queries/user/cryptoWallet.ts

append into #2447 fix/crypto_wallet

fake crypto_wallet entry need userId

---

src/queries/user/cryptoWallet.ts

append to #2447 fix/crypto_wallet

use userId as id key for `hasNFTs` redis caching layer

---

src/mutations/user/walletLogin.ts

when viewer.ethAddress is not null, this should not go into wallet link logic;
https://auth.matters.news/login?... has a logic to re-login when linking to like.co,
wallet re-login should work same as email re-login: ignore whatever in the viewer
also archive the crypto_wallet at time of wallet link,
supercedes #2450

fix/wallet-login: should allow re-login of same account

---

package-lock.json
package.json

fix(ipfs): ipfs path in metadata

---

package-lock.json
package.json
src/connectors/gcp/index.ts

it has triggered many good gmail registration requests flagged as bot, need logs to know why

fix(): skip recaptcha checking bot traffic

---

src/common/errors.ts
src/connectors/gcp/index.ts
src/connectors/userService.ts

fix https://github.com/thematters/matters-server/issues/2460

fix: error type for login user without password

---

src/queries/draft/article/drafts.ts

Reverts thematters/matters-server#2470

Revert "[hotfix -develop] fix: revert draft.article.drafts"

---

.github/workflows/deploy.yml

always run `apt-get update` before install anything

always run `apt-get update`

---

src/common/enums/index.ts
src/queries/article/index.ts
src/queries/article/summary.ts

fix(summary): do not fallback to make summary for paywall'ed content

---

schema.graphql
src/common/utils/initSearchIndices.ts
src/connectors/baseService.ts
src/connectors/tagService.ts
src/definitions/index.d.ts
src/definitions/schema.d.ts
src/queries/draft/article/drafts.ts
src/queries/system/search.ts
src/types/article.ts
src/types/system.ts

also have a boolean tag to include authors' frequently used tags
resolves #2490
- [Server] - Default tag recommendation for tag selector

feat(search-tags): search tags in order of num articles descending

---

.husky/pre-commit
knexfile.js

to show up name in DB server side

feat(application_name): add application_name in connection string

---

src/common/enums/index.ts
src/queries/article/index.ts

fix(): update TagSearchResult type with global id

---

.gitignore
schema.graphql
src/common/enums/index.ts
src/common/errors.ts
src/common/utils/__test__/text.test.ts
src/common/utils/text.ts
src/common/utils/validator.ts
src/connectors/__test__/tagService.test.ts
src/connectors/baseService.ts
src/connectors/queue/publication.ts
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/article/putTag.ts
src/mutations/draft/putDraft.ts
src/types/draft.ts

- add stripPunctPrefixSuffix; same as in thematters/matters-web#2450
- remove isValidTagName
resolves #2490

fix(tag-create): do not allow tag content begin or ends with punct

---

src/mutations/draft/putDraft.ts
src/types/__test__/draft.test.ts

use a small helper `sanitizeTags` to handle all cases;
- do not update tags if not provided in parameters

fix(omit-set-tags): change resetTags to omitTags at the beginning

---

package-lock.json
package.json
schema.graphql
src/common/utils/__test__/text.test.ts
src/common/utils/text.ts
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/queries/article/index.ts
src/queries/article/tag/articles.ts
src/queries/article/tag/tagArticlesSearchResult.ts
src/types/article.ts

[Sever] - API for trending feed in tag's page

---

db/migrations/20220420023434_update_curation_tag_materialized.js

feat: update algorithm for curated tag list

---

schema.graphql
src/common/enums/index.ts
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/queries/article/index.ts
src/queries/article/tag/recommended.ts
src/types/article.ts

[Server] - API of related tags recommendation in tag page

---

db/migrations/20220510080000_add_iscn_publish_to_article.js
schema.graphql
src/common/enums/queue.ts
src/connectors/likecoin/index.ts
src/connectors/queue/baseQueue.ts
src/connectors/queue/ipfs.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/article/publishArticle.ts
src/mutations/circle/putCircleArticles.ts
src/mutations/draft/putDraft.ts
src/types/article.ts
src/types/circle.ts
src/types/draft.ts

feat/iscn-publishing: [Server] - ISCN implementation

---

.github/workflows/test.yml
package-lock.json
src/common/enums/cors.ts

feat(cors-allow-vercel-preview): part-i: [Server] - CORS readonly

---

src/common/utils/updateWordCount.ts
src/connectors/queue/revision.ts

Total word count is incorrect #2493

feat(update-word-count): update case of word count in revision

---

.github/workflows/deploy.yml
.github/workflows/test.yml
db/migrations/20220621013529_update_hottest_feed_boost_list.js
db/seeds/04_draft.js
package-lock.json
package.json
src/common/enums/cors.ts
src/common/errors.ts
src/common/utils/connections.ts
src/common/utils/updateWordCount.ts
src/connectors/likecoin/index.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/mutations/article/editArticle.ts
src/queries/user/recommendation/newest.ts
src/types/__test__/article.test.ts
src/types/__test__/utils.ts

major changes:
- ISCN
- Tags Hottest feed

Release 4.3.0

---

docker/Dockerfile
package-lock.json
package.json

other test CI already in-use 0bda5270d
https://github.com/thematters/matters-server/blob/develop/.github/workflows/test.yml#L61

use npm install --force

---

.github/workflows/schema.yml
package-lock.json
package.json
src/connectors/likecoin/index.ts
src/mutations/article/editArticle.ts
src/queries/user/recommendation/newest.ts

release/4.3.2 
- fix a dup-revised articles problem

release/4.3.2 

---

package-lock.json
package.json
src/connectors/likecoin/index.ts
src/connectors/tagService.ts

turn off some logging
- for follow tags: catch the error only when exception happens

merge back to web-dev: turn off some logging

---

src/connectors/queue/publication.ts
src/connectors/tagService.ts
src/queries/article/tag/articles.ts
src/queries/article/tag/recommended.ts

feat(tags): show better related tags for new created

---

db/migrations/20220617180000_alter_notify_setting.js
schema.graphql
src/common/enums/notification.ts
src/connectors/__test__/notificationService.test.ts
src/connectors/notificationService/notice.ts
src/definitions/notification.d.ts
src/definitions/schema.d.ts
src/mutations/circle/toggleFollowCircle.ts
src/mutations/comment/putComment.ts
src/queries/notice/index.ts
src/types/notice.ts
src/types/user.ts

feat(): Circle notifications

---

src/common/enums/table.ts
src/connectors/tagService.ts
src/queries/user/recommendation/tags.ts
src/types/__test__/user.test.ts

feat(): Update API of all tag pages recommendation

---

src/connectors/tagService.ts
src/queries/user/recommendation/tags.ts

feat(tags-url): Update API of all tag pages recommendation

---

src/common/enums/index.ts
src/common/utils/__test__/text.test.ts
src/common/utils/text.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/mutations/article/editArticle.ts
src/mutations/article/putTag.ts
src/mutations/draft/putDraft.ts
src/types/__test__/draft.test.ts
src/types/__test__/tag.test.ts

feat(regex): validation pattern for new tag naming rules

---

src/connectors/mail/index.ts
src/connectors/notificationService/mail/sendDailySummary.ts
src/connectors/notificationService/mail/sendVerificationCode.ts

to use whatever settings in the console;

feat(sendgrid-clicks): turn off extra settings

---

schema.graphql
src/common/enums/action.ts
src/connectors/baseService.ts
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/mutations/user/index.ts
src/mutations/user/togglePinTag.ts
src/types/article.ts
src/types/user.ts

also changed some to TagSearchResultConnection

feat(pin-tag): add action pin into action_tag

---

src/connectors/tagService.ts

this is temporary because #2623 need a knex upgrade

fix(): check from public.tag instead of rollup

---

schema.graphql
src/definitions/schema.d.ts
src/queries/article/index.ts
src/queries/article/tag/tagArticlesSearchResult.ts
src/types/article.ts

for front-end easier to handle the transition.

feat(embed-tag): embed tag inside tagSearchResult

---

schema.graphql
src/connectors/notificationService/index.ts
src/definitions/notification.d.ts
src/definitions/schema.d.ts
src/queries/notice/index.ts
src/types/notice.ts

Circle notifications partIII: some missed cases

---

schema.graphql
src/connectors/notificationService/notice.ts
src/connectors/queue/publication.ts
src/connectors/userService.ts
src/definitions/notification.d.ts
src/definitions/schema.d.ts
src/mutations/comment/putComment.ts
src/queries/notice/index.ts
src/types/notice.ts

cases for read notice type mappings

---

src/queries/comment/downvotes.ts
src/types/__test__/comment.test.ts
src/types/comment.ts

Return 0 when querying the downvote counts

feat(downvote): downvote counts return 0

---

src/connectors/tagService.ts

fix https://github.com/thematters/matters-server/pull/2648

fix(tag): fix `tagService.countAuthors`

---

src/common/utils/connections.ts
src/connectors/tagService.ts
src/queries/article/tag/recommended.ts
src/queries/user/recommendation/tags.ts

1. sort by r2w instead of r1w;
2. not to include the exact tag itself in related search;

fix(related-tags): update related tags search

---

src/common/enums/notification.ts
src/connectors/__test__/notificationService.test.ts
src/connectors/notificationService/index.ts
src/connectors/notificationService/mail/sendDailySummary.ts
src/connectors/notificationService/notice.ts
src/connectors/queue/emails.ts
src/definitions/notification.d.ts
src/mutations/comment/putComment.ts
src/queries/notice/index.ts

use either circle_member_new_broadcast (to owner) and in_circle_new_broadcast (to other participants)

deprecated: 'circle_new_broadcast', // deprecated

---

src/connectors/paymentService.ts

fix: returning('id') does not return integers in knex v2.1

---

src/connectors/likecoin/index.ts
src/mutations/article/appreciateArticle.ts

with iscn_id if available:
https://api.docs.like.co/#35e55922-559d-4bda-974f-5465fe023f48

feat(superlike-iscn): superlike with short url encoding

---

README.md

fix https://github.com/thematters/matters-server/issues/2675

fix(docs): fix README setup guide

---

src/connectors/tagService.ts

- also move countArticles closer to findArticleIds, these 2 should
share a chunk of similar code

fix(tag-articles): order by article.id desc, not article_tag.id

---

src/common/enums/index.ts
src/common/utils/__test__/text.test.ts
src/common/utils/text.ts
src/connectors/notificationService/index.ts
src/connectors/queue/publication.ts
src/connectors/tagService.ts
src/mutations/article/editArticle.ts
src/mutations/article/putTag.ts
src/mutations/draft/putDraft.ts
src/types/__test__/tag.test.ts

sync with thematters/matters-web#2710 ; also add description length check

feat(tag-length): update max tag length to 50

---

package-lock.json
package.json

fix https://github.com/thematters/matters-server/issues/2672

fix(ipfs content):  bump @matters/matters-html-formatter version

---

schema.graphql
src/connectors/articleService.ts
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/queries/article/relatedArticles.ts
src/queries/article/user/articles.ts
src/types/user.ts

feat(articles-by-tags): API for user profile tags

---

.github/workflows/deploy.yml
.github/workflows/test.yml
docker/docker-compose.yml
package-lock.json
package.json
src/connectors/articleService.ts

fix(ipfs-client): update server to be able use latest go-ipfs

---

src/common/enums/cookie.ts
src/common/utils/cookie.ts

https://github.com/thematters/matters-web/issues/2623

feat(i18n): set `__language` cookie on user login/signup

---

src/connectors/queue/revision.ts
src/mutations/article/editArticle.ts

fix(iscn): fix some cases re-register iscn even not checked in revising

---

src/common/utils/cookie.ts

Reverts thematters/matters-server#2722

Revert "fix(i18n): set language cookie on hostname"

---

schema.graphql
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/queries/user/index.ts
src/queries/user/tags/tagsUsageRecommendation.ts
src/types/user.ts

fix(author-tags-order): actual usage order instead of creation order

---

package-lock.json
package.json
schema.graphql
src/connectors/tagService.ts
src/definitions/schema.d.ts
src/queries/article/tag/recommended.ts
src/queries/user/index.ts
src/queries/user/tags/tagsUsageRecommendation.ts
src/types/user.ts

- fix(author-tags-order): actual usage order instead of creation order; resolve #2720

HotRelease/4.4.1: fix some tags recommendation

---

src/connectors/tagService.ts

fix(count-tag-articles): await fallback read article_tag

fix(count-tag-articles): await read fallback article_tag

---

src/queries/article/tag/numArticles.ts

resolve thematters/matters-web#2760

fix(tag-count): use numArticles instead

---

src/mutations/article/appreciateArticle.ts
src/mutations/article/readArticle.ts
src/queries/article/canSuperLike.ts

https://matters.news/${userName}/${articleId}

fix(superlike-short-id): use all short id form for depub.space

---

db/migrations/20220919210000_create_user_ipns_keys_table.js
src/connectors/articleService.ts
src/connectors/queue/publication.ts
src/connectors/tagService.ts

feat(ipns-publishing): save both last_data_hash & last_published

---

src/connectors/articleService.ts
src/connectors/queue/publication.ts

fix(content-data-hash): update last cid

---

src/connectors/feed/index.ts

feat(ipns-feed): both xml and index.html

---

src/routes/graphql.ts

It works in dev environment, now hot release to production.

[hot release] feat(gql): enable `sendVariableValues` for usage reporting

---

src/routes/graphql.ts

Reverts thematters/matters-server#2767

Revert "[hot release] feat(gql): enable `sendVariableValues` for usage reporting"

---

package-lock.json
package.json
src/common/utils/text.ts
src/connectors/feed/index.ts
src/connectors/ipfs/index.ts

feed/index should be moved to bundler

fix(ipns-feed): feed index

---

src/routes/graphql.ts

Reverts thematters/matters-server#2757

Revert "feat(gql): enable `sendVariableValues` for usage reporting"

---

src/connectors/feed/index.ts
src/connectors/tagService.ts

fix(log): turn off prior existing logging lines

---

src/connectors/articleService.ts
src/connectors/queue/publication.ts

only append the `latestArticleDataHash` once only, to save from timeout

fix(ipns-publishing): change to re-use previous published lastDataHash

---

src/connectors/articleService.ts
src/connectors/queue/publication.ts

only OSS mode still attach the given number of articles

fix(ipns-publihsing): incremental? mode for latest 1 article publihsing

---

db/migrations/20220927090006_create_user_tags_order.js
schema.graphql
src/definitions/index.d.ts
src/definitions/schema.d.ts
src/mutations/user/index.ts
src/mutations/user/putFeaturedTags.ts
src/queries/user/featuredTags.ts
src/queries/user/index.ts
src/types/user.ts

feat(user-saved-tags): [Server] API for user profile tags

---

src/connectors/feed/index.ts

both xml and index.html to be more compliant to standards

feat(ipns-index): enrichment with matters author link

---

schema.graphql
src/definitions/schema.d.ts
src/queries/article/availableTranslations.ts
src/queries/article/canSuperLike.ts
src/queries/article/index.ts
src/types/article.ts

* add `Article.availableTranslations`;
* fix article id of `Article.canSuperlike` resolver; @tx0c

feat(i18n): add `Article.availableTranslations`

---

src/queries/user/recommendation/newest.ts

fix(newest): Couldn't find published article in the latest feed

---

src/queries/article/relatedArticles.ts

should resolve #2823 and figure out where originates the duplicates

fix(related-dedup): Remove current article from article recommendation

---

src/mutations/system/deleteAnnouncements.ts

Delete announcement should delete the corresponding translation together

fix(announcement): delete announcement translation

---

src/mutations/system/deleteAnnouncements.ts

Reverts thematters/matters-server#2864

Revert "fix(announcement): delete announcement translation"

---

src/common/utils/text.ts
src/connectors/feed/index.ts

TODO: move as utils to html-formatter

fix(utf8-xml): strip all white spaces and non-printable character

---

src/connectors/tagService.ts

remove choice tag from recommendation and search

---

db/migrations/20221018050411_update_hottest_feed_boost_usdt.js

chore: update hottest view with usdt support

---

src/connectors/__test__/payToQueue.test.ts
src/connectors/queue/payTo/payToByBlockchain.ts

- use bull backoff retry to polling blockchain tx instead of using ethers `waitForTransation`  to decreate requests number
- add delay for polling

feat(paytoqueue): use bull backoff retry

---

schema.graphql
src/definitions/schema.d.ts
src/queries/user/index.ts
src/types/user.ts

revert part logic from 6ef2163 from #2725
resolve #2838

feat(maintained-tags): Fix user page tags query logics

---

src/connectors/__test__/payToByBlockchainQueue.test.ts
src/connectors/queue/payTo/payToByBlockchain.ts

- fix re-sending
- turn off slack normal notification in repeat job

fix re-sending notificatoin of succeeded donation

---

.env.example
src/common/environment.ts
src/connectors/articleService.ts
src/connectors/aws/index.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/mutations/article/updateArticleState.ts

feat(sqs-notify): move PublishToIPFS to optional phase, publish SQS

---

schema.graphql
src/definitions/schema.d.ts
src/types/article.ts

Handle article ipfs hash null thematters/matters-web#2882

feat(allow-hash-null): change dataHash / mediaHash to be optional

---

src/routes/pay/likecoin.ts

Reverts thematters/matters-server#2927

Revert "fix(likecoin): add loggers to like pay webhook"

---

src/routes/pay/likecoin.ts

Reverts thematters/matters-server#2926

Revert "fix: minor"

---

src/routes/pay/likecoin.ts

Reverts thematters/matters-server#2925

Revert "fix(likecoin): revert likecoin webhook refactoring"

---

.gitignore
db/migrations/20221111164251_alter_user_add_currency.js
schema.graphql
src/definitions/schema.d.ts
src/mutations/user/index.ts
src/mutations/user/setCurrency.ts
src/queries/exchangeRates.ts
src/queries/index.ts
src/queries/user/index.ts
src/types/__test__/user.test.ts
src/types/payment.ts
src/types/user.ts

- impl currency preference setting api
- mock currency exchange rates api

add currency convertor related api

---

src/connectors/articleService.ts
src/connectors/ipfs/index.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/connectors/tagService.ts
src/mutations/article/editArticle.ts
src/queries/article/summary.ts
src/queries/circle/works.ts
src/types/__test__/user.test.ts
tests/k6.js

fix(publication): fix unable to put article into paywall

---

schema.graphql
src/definitions/schema.d.ts
src/queries/user/notification.ts
src/types/__test__/user.test.ts
src/types/user.ts

ref https://mattersnews.slack.com/archives/C88CK7Q7L/p1668431461624039?thread_ts=1668428211.341869&cid=C88CK7Q7L

fix(settings): update schema to let settings.notification nullable

---

src/common/enums/verification.ts
src/common/errors.ts
src/connectors/userService.ts
src/mutations/user/changeEmail.ts
src/mutations/user/confirmVerificationCode.ts
src/mutations/user/resetPassword.ts
src/mutations/user/userRegister.ts
src/mutations/user/walletLogin.ts
src/types/__test__/user.test.ts

* increase expiration time of email verification;
* add `CODE_INACTIVE` error;
* revise verification code checkers;

feat(verification-code): increase expiration time of email verification

---

schema.graphql
src/connectors/__test__/paymentService.test.ts
src/connectors/__test__/utils.ts
src/connectors/paymentService.ts
src/definitions/schema.d.ts
src/queries/user/wallet/transactions.ts
src/types/__test__/user.test.ts
src/types/payment.ts

impl transactions filtering api

---

package-lock.json
package.json
src/common/utils/content.ts
src/connectors/__test__/articleService.test.ts
src/connectors/articleService.ts
src/connectors/feed/index.ts
src/connectors/notificationService/mail/utils.ts
src/connectors/notificationService/translations/index.ts
src/connectors/queue/migration.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/mutations/article/editArticle.ts
src/queries/article/language.ts
src/queries/article/summary.ts
src/queries/article/translation.ts
src/queries/draft/index.ts

https://github.com/thematters/ipns-listen-repub/issues/5

feat(ipfs): replace `@matters/matters-html-formatter` with `@matters/ipns-site-generator`

---

schema.graphql
src/connectors/alchemy/index.ts
src/definitions/index.d.ts
src/definitions/schema.d.ts
src/queries/user/nfts.ts
src/types/user.ts
tests/k6.js

[Issue](https://github.com/thematters/matters-web/issues/2919)

fix(avatar-404): use alchemy to fetch nft image

---

src/types/__test__/circle.test.ts

feat(test-cases): Add test cases for article accessibility

---

db/bin/refresh-lasts.sh
db/sql/create-materialized-view-search-index-tag.sql
db/sql/create-materialized-view-search-index-user.sql

partially resolve #2973; but main indexer work is in thematters/ipns-listen-repub#7

feat(unit-tests): indexer for the Search-Rework

---

.env.example
src/common/environment.ts
src/connectors/aws/index.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/mutations/article/editArticle.ts

partly for Search articles with new Search-Rework Algorithms#2972

feat(sns-fanout): call sns publish messages fanout to multiple sqs

---

schema.graphql
src/connectors/articleService.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/connectors/tagService.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/queries/system/search.ts
src/types/system.ts

for both:
- Search articles with new Search-Rework Algorithms #2972
- QuickSearch of User & Tag #2971

feat(search-api): search api version flag

---

src/connectors/cache/index.ts
src/connectors/likecoin/index.ts
src/connectors/queue/likecoin.ts
src/mutations/article/readArticle.ts
src/queries/user/liker/civicLiker.ts

Fix `isCivicLiker` query resolver and queue:
* Set a timeout (2000ms);
* Use unique id as queue job id;
* Remove job after complete or failed;

fix(liker): set timeout for isCivicLiker query

---

db/seeds/06_tags.js
db/testSetup.js
package-lock.json
package.json
src/common/utils/__test__/text.test.ts
src/common/utils/text.ts
src/connectors/__test__/tagService.test.ts
src/connectors/__test__/userService.test.ts
src/connectors/tagService.ts
src/connectors/userService.ts
src/queries/system/search.ts

- fix db setup script for tests with native database 
- preprocess searchV1 input (t2s, lowercase, strip spaces) 
- impl `UserService.searchV1`
- impl `TagService.SearchV1`
resolve https://github.com/thematters/matters-server/issues/2971

impl new version user & tag search

---

src/common/environment.ts
src/connectors/articleService.ts
src/connectors/baseService.ts

for Search articles with new Search-Rework Algorithms #2972

feat(articles-search): use meilisearch #3028

---

src/connectors/__test__/userService.test.ts
src/connectors/articleService.ts
src/connectors/cache/index.ts
src/connectors/userService.ts

fix `Userservice.updateLastSeen` caching

---

src/connectors/articleService.ts

feat(articles-searchkey): change to use the converted key

---

package.json
src/connectors/articleService.ts
src/connectors/ipfs/index.ts
src/connectors/userService.ts

➸ git log --oneline --reverse origin/master..origin/develop
718e49ad fix(comment): fix `Comment.fromDonator`
b5707e4d feat(search-articles): add sort by 'numViews:desc'
ec87d719 (feat(search-ilike): search user_name with ilike instead

HotRelease/4.12.1 Comment.fromDonator & search features

---

src/connectors/tagService.ts

fix(remove-keyorgin): remove original key in search order

---

src/connectors/articleService.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts

some cases articles revision did not propagate to IPNS publishing #3012

fix(revising): remove target and retry with other node

---

src/connectors/userService.ts

revert(search-ilike): search user_name with ilike instead

---

package-lock.json
package.json
src/common/utils/cookie.ts
src/common/utils/index.ts

Also revised the client-side logic: https://github.com/thematters/matters-web/pull/3121

feat(cookie): set cookie to ".matters.news" for production

---

.platform/confighooks/postdeploy/map_parameters_to_env_vars.sh
.platform/hooks/postdeploy/map_parameters_to_env_vars.sh

for more info, see
https://www.notion.so/matterslab/Elastic-Beanstalk-Read-envs-from-SSM-Parameter-Store-87acd49624dc41989edc479fa860190c

ci(envs): let app read ENVS from AWS Systems Manager Parameter Store

---

.env.example
src/common/environment.ts
src/connectors/atomService.ts
src/connectors/baseService.ts
src/connectors/cloudflare/index.ts
src/connectors/index.ts
src/connectors/medium/index.ts
src/connectors/queue/asset.ts
src/connectors/systemService.ts
src/mutations/system/singleFileUpload.ts
src/mutations/user/updateUserInfo.ts
src/routes/img-cache/index.ts

for Revise API for backward compatible with Cloudflare Images #3068

feat(cfsvc): upload images to both Cloudflare & S3

---

src/mutations/user/userRegister.ts

Same as https://github.com/thematters/matters-server/blob/develop/src/mutations/user/userLogin.ts#L30-L32 did.

feat(context): overwrite `context.viewer` on userRegister success

---

src/mutations/circle/putCircle.ts
src/types/__test__/user.test.ts

Also, added tests for `updateUserInfo`

fix(name): allow admin to use reserved names as circle name

---

src/connectors/aws/index.ts
src/connectors/likecoin/index.ts

Revert "Revert "feat(likecoin): likecoin like use fifo queue to achieve exactly-once processing""
This reverts commit b45acc458e55206793026c1fd11d7c986c6d2327.

fix(likecoin):  likecoin.like do not invoke lambda successfully

---

db/bin/refresh-lasts.sh
db/sql/create-table-search-index-article.sql
db/sql/create-table-search-index-parser.sql
db/sql/create-table-search-index-tag.sql
db/sql/create-table-search-index-user.sql
src/common/environment.ts
src/connectors/__test__/tagService.test.ts
src/connectors/articleService.ts
src/connectors/tagService.ts
src/connectors/userService.ts

- add articleSearch with state and author_state filters
- add userService with description rank
- add tagService with description rank

feat(search-pg): search v1 improvements

---

db/migrations/20230222163919_alert_article_read_count_created_at_index.js
db/migrations/20230227092229_alert_article_hottest_materialized_score_index.js
db/migrations/20230227142016_alert_draft_created_at_index.js
src/connectors/__test__/articleService.test.ts
src/connectors/articleService.ts
src/queries/article/appreciationsReceived.ts
src/queries/user/recommendation/hottest.ts
src/types/__test__/user.test.ts

https://www.notion.so/matterslab/SQL-Tuning-db4ae72cb85f4bfeab0ef7e2f157f0ce

perf: sql tuning

---

src/connectors/__test__/articleService.test.ts
src/connectors/articleService.ts
src/queries/article/appreciationsReceived.ts

return correct count when first=0 in appreciationsReceiverd resolver

fix(appreciations): return correct count when first=0 

---

src/common/enums/cache.ts
src/connectors/articleService.ts
src/connectors/atomService.ts

partly for IPFS occasionally on development #3172

fix(user-ipns-keys): fix updated_at timestamp of user_ipns_keys

---

src/common/enums/cache.ts
src/connectors/articleService.ts
src/connectors/atomService.ts
src/connectors/tagService.ts
src/connectors/userService.ts

feat(pg-search-by-score): tag & user full text search first order by score

---

db/migrations/20230307172508_alert_draft_add_can_comment.js
schema.graphql
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/draft/putDraft.ts
src/types/__test__/article.test.ts
src/types/__test__/draft.test.ts
src/types/__test__/utils.ts
src/types/article.ts
src/types/draft.ts

feat(article-response-setting): add `canComment` to article/draft API

---

package.json

context: https://mattersnews.slack.com/archives/C7Y38U4DA/p1678681818246539

ci: limit node version to 16

---

src/connectors/articleService.ts

revert(fdd8c4be): remove title_like_rank

---

schema.graphql
src/common/utils/IERC1271.ts
src/definitions/schema.d.ts
src/mutations/user/walletLogin.ts
src/queries/draft/article/newestUnpublishedDraft.ts
src/queries/draft/index.ts
src/types/__test__/article.test.ts
src/types/article.ts

https://github.com/thematters/matters-web/issues/3292

feat(article): implement `ArticlenewestPublishedDraft` and `Article.newestUnpublishedDraft`

---

src/common/enums/index.ts
src/mutations/article/editArticle.ts
src/mutations/draft/putDraft.ts
src/types/__test__/article.test.ts
src/types/__test__/draft.test.ts

- change `MAX_TAGS_PER_ARTICLE_LIMIT` to 3
- tags can decrease when its amount out of limit
- fix undefined colleciton/tags handling logic
- refactoring

feat: change tags handling logic

---

src/connectors/articleService.ts

difference between failed IPNS update and succeeded

feat(record-timestamps): use updated_at & last_published_at to query

---

src/connectors/likecoin/index.ts

https://mattersnews.slack.com/archives/CC032ME07/p1679361345285349

fix(likecoin): fix response handler of superlike

---

src/connectors/articleService.ts
src/queries/user/articleCount.ts
src/queries/user/totalWordCount.ts
src/types/__test__/article.test.ts
src/types/__test__/user.test.ts

* archive articles linked to same draft;
* de-dup `User.status.totalWordCount` and `User.status.articleCount`;

fix(article): archive articles linked to same draft

---

src/connectors/userService.ts
src/mutations/user/updateUserInfo.ts
src/mutations/user/userRegister.ts
src/types/__test__/user.test.ts

https://github.com/thematters/matters-server/pull/3261

feat(username): lowercase username and case-insensitive query username

---

schema.graphql
src/common/enums/notification.ts
src/common/utils/notice.ts
src/connectors/__test__/notificationService.test.ts
src/connectors/notificationService/index.ts
src/connectors/notificationService/notice.ts
src/definitions/notification.d.ts
src/definitions/schema.d.ts
src/queries/notice/index.ts
src/types/notice.ts

Also, fixed the missing actor id of CommentPinned notice

feat(notice): remove PaymentPayout notice

---

db/migrations/20230406025628_create_user_restriction_table.js
schema.graphql
src/connectors/__test__/userService.test.ts
src/connectors/userService.ts
src/definitions/index.d.ts
src/definitions/schema.d.ts
src/mutations/system/index.ts
src/mutations/system/putRestrictedUsers.ts
src/queries/system/oss/articles.ts
src/queries/system/oss/badgedUsers.ts
src/queries/system/oss/comments.ts
src/queries/system/oss/index.ts
src/queries/system/oss/oauthClients.ts
src/queries/system/oss/restrictedUsers.ts
src/queries/system/oss/seedingUsers.ts
src/queries/system/oss/skippedListItems.ts
src/queries/system/oss/tags.ts
src/queries/system/oss/users.ts
src/queries/user/index.ts
src/queries/user/oss.ts
src/queries/user/recommendation/hottest.ts
src/queries/user/recommendation/newest.ts
src/types/__test__/system.test.ts
src/types/__test__/user.test.ts
src/types/system.ts
src/types/user.ts

- add db migration
- update graphQL schema
-  impl related resolvers
- refactors
resolve #3243

feat: impl oss user restriction

---

src/common/enums/cors.ts

for thematters/developer-resource#207
this is necessary for any https://web-stage.matters.town/ town site access

feat(adapt-hostname): Matters.Town Setup (4/17) #207

---

src/connectors/aws/index.ts

// Unable to load NFT avatar fixes #3255

fix(nft-img-url): add new alchemy NFT image url

---

src/mutations/user/generateSigningMessage.ts

use ${environment.siteDomain} to construct website link

feat(in-wallet): allow both .news & .town domain

---

db/migrations/20230419211549_correct_duplicate_articles.js
src/connectors/queue/__test__/publication.test.ts
src/connectors/queue/publication.ts

fix(publication): specify job id to avoid duplicate articles

---

src/connectors/notificationService/mail/sendAdoptTag.ts
src/connectors/notificationService/mail/sendAssignAsTagEditor.ts
src/connectors/notificationService/mail/sendCircleInvitation.ts
src/connectors/notificationService/mail/sendMigrationSuccess.ts
src/connectors/notificationService/mail/sendPayment.ts
src/connectors/notificationService/mail/sendRegisterSuccess.ts
src/connectors/notificationService/mail/sendUserDeletedByAdmin.ts
src/connectors/notificationService/mail/sendVerificationCode.ts

https://github.com/thematters/matters-email/issues/201

feat(email): send `copyrightYear` as variable to sendgrid templates

---

db/afterEnvTestSetup.js
jest.config.js
package-lock.json
package.json
src/common/utils/index.ts
src/connectors/queue/__test__/payToByBlockchain.test.ts
src/connectors/queue/__test__/publication.test.ts
src/connectors/queue/payTo/blockchain.ts
src/connectors/queue/payTo/matters.ts
src/connectors/queue/publication.ts

https://github.com/thematters/matters-server/pull/3239  prior PR did not  fix the problem brought by global queue state,  as there are async tasks during each tests. 
This time, we give each queues their own redis instances.

test(queue): isolate queue state between tests by assign exclusive redis instances

---

src/common/utils/index.ts
src/mutations/system/putAnnouncement.ts
src/mutations/system/singleFileUpload.ts
src/queries/article/assets.ts
src/queries/article/cover.ts
src/queries/article/tag/cover.ts
src/queries/article/topic/cover.ts
src/queries/circle/avatar.ts
src/queries/circle/cover.ts
src/queries/draft/assets.ts
src/queries/draft/cover.ts
src/queries/oauthClient/avatar.ts
src/queries/system/official/announcements.ts
src/queries/system/official/translations.ts
src/queries/user/avatar.ts
src/queries/user/profileCover.ts
src/routes/img-cache/index.ts

Reverts thematters/matters-server#3318

Revert "[hot-release] feat(image): add admin check into useS3 conditon"

---

package-lock.json
package.json

from Revise ipns-site-generator for Matters.Town#141 with thematters/ipns-site-generator#142
resolve thematters/ipns-site-generator#141

feat(update-ipns-pkg): update ipns site manager

---

package-lock.json
package.json

https://github.com/thematters/matters-editor/pull/425/commits/dfed36c0cfb1fde8ca2f38a28cb408e590b191cd

fix(editor): make sanitizer allows "embed" classname

---

src/connectors/exchangeRate/index.ts
src/middlewares/logger.ts
src/queries/article/index.ts
src/queries/draft/index.ts

- fix draftToArticle resolver  to return null when draft is in unpublished state
- add more context for resovler logging

fix(draft): fix draftToArticle resolver 

---

src/common/enums/verification.ts
src/connectors/userService.ts
src/definitions/index.d.ts
src/mutations/user/confirmVerificationCode.ts
src/mutations/user/sendVerificationCode.ts
src/types/__test__/user.test.ts

feat: revise verfication logic

---

package-lock.json
package.json

https://github.com/thematters/matters-editor/pull/425/commits/8b78a95808c30987d98f470af8fba2ad91d5d3af

fix(editor): add Mention extension to normalizers

---

package-lock.json
package.json

https://github.com/thematters/matters-editor/pull/425/commits/1025e647cc419ae83b17763fbddf5b7e260409a0
https://github.com/thematters/matters-editor/pull/425/commits/f62e63e51a3d1473ffb037e22623104547703b5b

fix(editor): support multiple/trailing blank lines

---

db/migrations/20230531100617_alter_draft_add_sensitive.js
schema.graphql
src/definitions/schema.d.ts
src/mutations/article/editArticle.ts
src/mutations/article/index.ts
src/mutations/article/updateArticleSensitive.ts
src/mutations/article/updateArticleState.ts
src/types/__test__/article.test.ts
src/types/article.ts

* Add `Article.sensitiveByAuthor` and `Article.sensitiveByAdmin`;
* Add `updateArticleSensitive` for admin (OSS);
* Revise `editArticle` to support `sensitive` input;

feat(article): add article sensitive fields and mutations

---

db/migrations/20230602150556_alter_draft_license.js
schema.graphql
src/common/enums/index.ts
src/definitions/schema.d.ts
src/mutations/circle/putCircleArticles.ts
src/mutations/draft/putDraft.ts
src/queries/article/index.ts
src/queries/draft/index.ts
src/types/__test__/circle.test.ts
src/types/__test__/draft.test.ts
src/types/article.ts

feat: add cc4.0 license

---

src/connectors/queue/revision.ts
src/mutations/article/editArticle.ts
src/mutations/circle/putCircleArticles.ts

Reverts thematters/matters-server#3079

Revert "feat(article-revision): increase revision count only if article content is edited"

---

src/mutations/article/editArticle.ts

https://github.com/thematters/matters-web/pull/3219/files#diff-039e6708c709aa912c128ed56f9388d9d4ea46db4a2988724bba40184e76fb2cR69-R72

feat(editor): align diff algorithm with new editor frontend

---

.env.example
schema.graphql
src/common/environment.ts
src/connectors/articleService.ts
src/connectors/tagService.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/queries/system/search.ts
src/types/system.ts

for thematters/developer-resource#221

feat(tsqi-search): Search Service Implementation

---

src/types/article.ts
src/types/collection.ts
src/types/comment.ts
src/types/system.ts
src/types/user.ts

* enable multi-level multiplier for `input.ids` and set the complexity of these mutations to `10`[1];
[1] We will apply this change to other mutation since writes are more expensive than read operations.

feat(limit): enable multi-level multiplier for `input.ids`

---

src/common/enums/index.ts
src/common/enums/notification.ts
src/common/enums/user.ts
src/connectors/__test__/notificationService.test.ts
src/connectors/notificationService/index.ts
src/connectors/notificationService/notice.ts
src/connectors/notificationService/translations/index.ts
src/connectors/slack/index.ts
src/connectors/userService.ts
src/mutations/user/updateUserState.ts
src/routes/pay/stripe/index.ts
src/types/__test__/auth.test.ts
src/types/__test__/user.test.ts
src/types/__test__/utils.ts

- refactor `updateUserState`  resolver
- auto ban high rick users

feat(payment): auto ban high risk users

---

src/connectors/articleService.ts
src/queries/article/user/articles.ts

Reverts thematters/matters-server#3451

Revert "fix(article): remove `stickyFirst` args of `ArticleService.findByAuthor`"

---

src/connectors/articleService.ts
src/queries/article/user/articles.ts

Reverts thematters/matters-server#3486

Revert "Revert "fix(article): remove `stickyFirst` args of `ArticleService.findByAuthor`""

---

db/migrations/20230727145613_alter_transaction_purpose.js
schema.graphql
src/common/enums/payment.ts
src/connectors/__test__/paymentService.test.ts
src/connectors/paymentService.ts
src/definitions/schema.d.ts
src/routes/__test__/transaction.test.ts
src/routes/pay/stripe/index.ts
src/routes/pay/stripe/transaction.ts
src/types/payment.ts

- dispute add pending state
- pending dispute will affect balance
- add payout-reversal Tx instead of marking original payout Tx state as failed
- update transaction types in API

feat: add new tx types

---

src/queries/user/collections.ts
src/queries/user/index.ts
src/types/__test__/1/collection.test.ts
src/types/__test__/2/auth.test.ts
src/types/__test__/2/user.test.ts

Reverts thematters/matters-server#3518

Revert "fix(user): viewer resolver return null instead of `{id: null}`"

---

db/migrations/20230807093625_alter_verification_code.js
package-lock.json
schema.graphql
src/common/enums/verification.ts
src/connectors/baseService.ts
src/connectors/notificationService/mail/utils.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/definitions/user.d.ts
src/mutations/user/emailLogin.ts
src/mutations/user/index.ts
src/mutations/user/sendVerificationCode.ts
src/mutations/user/setEmail.ts
src/mutations/user/setPassword.ts
src/mutations/user/setUserName.ts
src/mutations/user/socialLogin.ts
src/mutations/user/userLogin.ts
src/mutations/user/userRegister.ts
src/mutations/user/walletLogin.ts
src/queries/user/index.ts
src/queries/user/socialAccounts.ts
src/types/user.ts

- refactor   resolvers: userLogin, userRegister, walletLogin
- mock new apis

feat: new login mock api

---

src/mutations/user/emailLogin.ts
src/mutations/user/sendVerificationCode.ts
src/types/__test__/2/auth.test.ts

- throw OTP code errors over password errors
- shorten OTP expire in dev

feat(email-login): throw code related errors over password errors

---

src/mutations/user/sendVerificationCode.ts

https://github.com/thematters/matters-server/pull/3283

feat(recaptcha): enable recaptcha for sign up

---

src/routes/pay/stripe/index.ts

and print usename instead user id in slack alert

fix(payment): do not assume paymentIntent.charges will always have charges objects

---

src/common/utils/makeContext.ts
src/definitions/user.d.ts
src/queries/user/socialAccounts.ts
src/types/__test__/utils.ts

- fix Viewer typing
- move sentry related dead code
- fix `socialAccount` resolver

fix(user): fix Viewer typing

---

src/connectors/passphrases/index.ts
src/mutations/user/emailLogin.ts
src/types/__test__/2/auth.test.ts

* throw `PasswordInvalidError` instead of `CodeInvalidError` for `PassphrasesMismatchError`;

fix(auth): throw `PasswordInvalidError` for `PassphrasesMismatchError`

---

db/migrations/20230914084208_alter_user_activity_view.js
src/queries/user/recommendation/following/sql.ts

perf(user_activity_materialized): recreate view with fixed id 

---

db/migrations/20230914084208_alter_user_activity_view.js
src/queries/user/recommendation/following/sql.ts

fix https://github.com/thematters/matters-server/issues/3548

[hotfix-master] fix(user_activity_materialized):refresh lead to many dead tuples

---

package-lock.json
package.json

https://github.com/thematters/matters-editor/compare/v0.2.0...v0.2.2

fix(editor): remove className support for link extension

---

src/mutations/article/appreciateArticle.ts
src/mutations/user/sendVerificationCode.ts

* ignore error of Promise.all
* enable cloudflare turnstile for appreciateArticle mutation

fix(captcha): ignore error of Promise.all

---

src/connectors/__test__/userService.test.ts
src/connectors/userService.ts
src/mutations/user/sendVerificationCode.ts
src/mutations/user/socialLogin.ts
src/types/__test__/2/auth.test.ts

revert PR https://github.com/thematters/matters-server/pull/3617

feat: revert email checks on both emails and socialAccounts

---

src/common/utils/getViewer.ts
src/connectors/__test__/userService.test.ts
src/connectors/userService.ts
src/mutations/user/emailLogin.ts
src/mutations/user/socialLogin.ts
src/mutations/user/walletLogin.ts
src/types/__test__/2/user.test.ts
src/types/__test__/utils.ts

resolve ZN-0032 in https://paper.dropbox.com/doc/2023-09-1--CBLQLE8EkLXUeuZ5AikBMXnHAg-fu94LLGlitHs09dcj2YZI

fix: create user with language during register

---

db/migrations/20231009170404_archive_bad_articles.js
src/connectors/articleService.ts

resolve https://github.com/thematters/matters-web/issues/3828

fix(article): fix article feeds issues

---

db/migrations/20231027104825_correct_draft_license.js
src/mutations/article/editArticle.ts
src/mutations/draft/putDraft.ts
src/types/__test__/1/article.test.ts
src/types/__test__/1/draft.test.ts
src/types/article.ts

https://github.com/thematters/matters-server/pull/3655
https://feedback.matters.town/bug-reports/p/cc20

fix(draft): remove support for CC2 license 

---

db/migrations/20231027104825_correct_draft_license.js
src/mutations/article/editArticle.ts
src/mutations/draft/putDraft.ts
src/types/__test__/1/article.test.ts
src/types/__test__/1/draft.test.ts
src/types/article.ts

* remove support for CC2 license;
* migrate unpublished CC2 drafts' license to CC4
https://feedback.matters.town/bug-reports/p/cc20

[hotfix - master] fix(draft): remove support for CC2 license

---

db/migrations/20231101210000_alter_user_table_extra.js
schema.graphql
src/connectors/__test__/userService.test.ts
src/connectors/atomService.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/mutations/user/emailLogin.ts
src/mutations/user/index.ts
src/mutations/user/socialLogin.ts
src/mutations/user/updateUserExtra.ts
src/mutations/user/walletLogin.ts
src/types/user.ts

feat(user-referral): Referral storing #3662

---

src/connectors/__test__/articleService.test.ts
src/queries/article/user/articles.ts
src/types/__test__/1/article.test.ts

Reverts thematters/matters-server#3663

Revert "fix(user-articles): return empty list when others instead of authors …"

---

schema.graphql
src/connectors/__test__/articleService.test.ts
src/connectors/articleService.ts
src/definitions/schema.d.ts
src/queries/article/donationCount.ts
src/queries/article/index.ts
src/queries/article/readerCount.ts
src/queries/article/user/articles.ts
src/types/__test__/1/article.test.ts
src/types/__test__/2/user.test.ts
src/types/article.ts
src/types/user.ts

Reverts thematters/matters-server#3671

Revert "Revert "feat(myworks): api implement""

---

src/connectors/__test__/articleService.test.ts
src/queries/article/user/articles.ts
src/types/__test__/1/article.test.ts

Reverts thematters/matters-server#3670

Revert "Revert "fix(user-articles): return empty list when others instead of authors …""

---

db/migrations/20231101210000_alter_user_table_extra.js
schema.graphql
src/connectors/__test__/userService.test.ts
src/connectors/atomService.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/mutations/user/emailLogin.ts
src/mutations/user/index.ts
src/mutations/user/socialLogin.ts
src/mutations/user/updateUserExtra.ts
src/mutations/user/walletLogin.ts
src/types/user.ts

Reverts thematters/matters-server#3669

Revert "Revert "feat(user-referral): Referral storing #3662""

---

db/migrations/20231101210000_alter_user_table_extra.js
package.json
schema.graphql
src/connectors/__test__/userService.test.ts
src/connectors/atomService.ts
src/connectors/cloudflare/index.ts
src/connectors/userService.ts
src/definitions/schema.d.ts
src/mutations/system/directImageUpload.ts
src/mutations/user/emailLogin.ts
src/mutations/user/index.ts
src/mutations/user/socialLogin.ts
src/mutations/user/updateUserExtra.ts
src/mutations/user/walletLogin.ts
src/types/system.ts
src/types/user.ts

add mime params in `directImageUpload` mutation

Release: 4.26.3

---

src/connectors/articleService.ts
src/connectors/baseService.ts
src/connectors/collectionService.ts
src/connectors/commentService.ts
src/connectors/draftService.ts
src/connectors/likecoin/index.ts
src/connectors/notificationService/notice.ts
src/connectors/paymentService.ts
src/connectors/queue/migration.ts
src/connectors/queue/payout.ts
src/connectors/tagService.ts
src/connectors/userService.ts
tsconfig.json

- remove `strictPropertyInitialization=false` in tsconfig
- refactor service classes to pass build
- fix runtime problem in payout queue

fix(service): fix uninitialized properties in service/queue classes

---

src/connectors/cloudflare/index.ts

Error handling on Cloudflare Images resolve #3675

fix(image-types): check images' real mime-type with file-type

---

db/migrations/20231127080000_alter_user_badge.js
schema.graphql
src/definitions/schema.d.ts
src/queries/user/badges.ts
src/types/user.ts

fix thematters/developer-resource#326

feat(badges): Digital Nomad program

---

db/migrations/20231128080000_alter_announcement_table.js
package-lock.json
package.json
schema.graphql
src/connectors/atomService.ts
src/definitions/schema.d.ts
src/mutations/system/putAnnouncement.ts
src/queries/system/official/announcements.ts
src/types/system.ts

only show unexpired announcements // resolves #3691

feat(announcement-expiration): add expiredAt column for announcement;

---

src/mutations/article/publishArticle.ts
src/mutations/draft/putDraft.ts

[Discussion](https://matterslab.slack.com/archives/GA0R09FHN/p1702052612208469)

feat(draft): trim title and summary on putDraft

---

src/mutations/system/setBoost.ts

https://github.com/thematters/matters-server/commit/49682d96a56fe505f9ccf36a08594a6ea8a1e0ab#diff-183f3a2982732ccfb6c742d30dc969d7d7f83ecafb7aabe123138b9a3d146b82R25

fix(oss): fix setBoost response

---

db/migrations/20231221080000_update_hottest_feed-tag-boost.js

feat(tag_boost): use boost score to adjust score up or down

---

src/routes/facebook.ts

see https://developers.facebook.com/support/bugs/394404919672888/

feat(facebook): change status code to meet requirement from meta staff

---

src/connectors/__test__/articleService.test.ts
src/connectors/articleService.ts
src/queries/response/article/responses.ts
src/types/__test__/2/comment.test.ts

- fix resolver to return totalCount correctly
- fix to handle banned comment

fix(responses): fix response pagination

---

src/connectors/atomService.ts
src/connectors/queue/asset.ts
src/mutations/article/putTopic.ts
src/queries/article/translation.ts
src/queries/response/article/responses.ts

- bugfix
- add access modifiers on AtomService

fix(responses): fix pagination next page getting wrong

---

src/connectors/userService.ts

for detail, see commits message.

feat(facebook): handle multi app-scope-ids for same users and id_token not returned case

---

.github/workflows/deploy.yml
.github/workflows/schema.yml
.github/workflows/test.yml
docker/Dockerfile
package-lock.json
package.json
src/connectors/__test__/articleService.test.ts

feat(node-v18): Bump deps: Node.js 18.x

---

jest.config.js
package-lock.json
package.json
src/common/utils/__test__/counter.test.ts
src/connectors/__test__/userService.test.ts
src/connectors/__test__/utils.ts
src/connectors/queue/__test__/publication.test.ts
src/connectors/queue/publication.ts

- `ioredis-mock` replace `redis-memory-server` 
- resolve jest config warning: " ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. "

feat(test): replace redis mock deps

---

src/routes/pay/stripe/index.ts

Reverts thematters/matters-server#3800

Revert "[hotfix-master] fix(dispute): change dispute event type temporarily to create dispute tx"

---

src/common/enums/payment.ts
src/common/environment.ts
src/connectors/__test__/curationContract.test.ts
src/connectors/__test__/paymentService.test.ts
src/connectors/blockchain/baseContract.ts
src/connectors/blockchain/curation.ts
src/connectors/paymentService.ts
src/connectors/queue/__test__/payToByBlockchain.test.ts
src/connectors/queue/payTo/blockchain.ts
src/queries/user/transaction.ts

https://github.com/thematters/developer-resource/issues/374

fix(blockchain): lowercase contract address

---

db/seeds/08_comments.js
src/common/utils/connections.ts
src/connectors/__test__/commentService.test.ts
src/connectors/commentService.ts
src/queries/comment/article/comments.ts
src/queries/comment/circle/broadcast.ts
src/queries/comment/circle/discussion.ts
src/types/__test__/2/comment.test.ts

filter archived/banned comments except those which have active/collapsed sub comments.

fix(comments): filter archived / banned comments by default

---

db/migrations/20240219000030_alter_article_short_hash.js
db/seeds/05_articles.js
package-lock.json
package.json
schema.graphql
src/common/utils/index.ts
src/common/utils/nanoid.ts
src/connectors/articleService.ts
src/definitions/article.d.ts
src/definitions/schema.d.ts
src/queries/article/index.ts
src/queries/article/rootArticle.ts
src/queries/article/shortHash.ts
src/types/__test__/1/article.test.ts
src/types/article.ts

Revise article APIs to support querying by hash resolves #346

feat(short-hash): query article API by short hash

---

src/mutations/article/editArticle.ts

this bug was introduced in https://github.com/thematters/matters-server/pull/3786

fix(edit-article): fix reset circle to increase revision count

---

package-lock.json
package.json

https://github.com/thematters/matters-editor/issues/451

feat(editor): bump @matters/matters-editor for new comment formats and squeeze empty lines

---

src/types/__test__/2/auth.test.ts
src/types/__test__/2/user.test.ts
src/types/directives/auth.ts

Reverts thematters/matters-server#3832

Revert "fix(auth): fix to throw error when visitor query oss related apis"

---

src/queries/system/oss/articles.ts
src/queries/system/oss/comments.ts
src/queries/system/oss/users.ts

(cherry picked from commit d52286614543d0f7548dabb889b68ac915f15fab)

[hotfix-master] fix: correct oss api ordering

---

src/connectors/articleService.ts
src/mutations/draft/putDraft.ts

resolve https://github.com/thematters/developer-resource/issues/379

feat(article-connection): remove blocked users' restriction on connect the articles

---

src/queries/user/latestWorks.ts
src/types/__test__/1/collection.test.ts

resolve [PR-034](https://www.notion.so/matterslab/Bug-c4de98af8f0a45eb8908b7564c64837e)

feat(latest-works): return 4 articles to allow filtering in front-end

---

src/connectors/__test__/systemService.test.ts
src/connectors/systemService.ts

feat(report-comment): auto collapse reported comment conditionally

---

src/connectors/queue/appreciation.ts
src/definitions/index.d.ts
src/mutations/article/appreciateArticle.ts
src/queries/article/appreciationsReceivedTotal.ts

import type fail silently as `skipLibCheck` set true

fix(import): correct import path

---

src/connectors/__test__/collectionService.test.ts
src/connectors/collectionService.ts
src/queries/user/latestWorks.ts

re [PR-68](https://www.notion.so/matterslab/74b5efcf02a34dc8b53a90ba3de6cd9a)

feat(latest-works): latest works return collections ordered by `updated_at` and not empty

---

src/mutations/comment/updateCommentsState.ts

fix(comment): invalidate comments' articles cache after updating state

---

schema.graphql
src/connectors/paymentService.ts
src/definitions/schema.d.ts
src/queries/article/donated.ts
src/queries/article/index.ts
src/queries/article/replyToDonator.ts
src/types/__test__/1/editArticle.test.ts
src/types/article.ts

feat(reply-to-donator): allow users read reply-to-donator message right after donation

---

src/connectors/queue/appreciation.ts

fix(article): allow author to appreciate their own articles

---

db/migrations/20240228155918_migrate_article_versioning_data_2.js
db/migrations/20240418111207_migrate_draft_asset_map.js

Reverts thematters/matters-server#3932

Revert "Revert: delete asset map and remigrate migration "

---

src/connectors/articleService.ts

(cherry picked from commit 39c41d75ead3730ff59c4eedf335475fbd467803)

[hotfix-master] fix(search): call wrong dataloader

---

src/connectors/queue/publication.ts

https://github.com/thematters/matters-server/commit/1861c2e5d8dbb5dd101d443b34f58543564ec1fd#diff-ad85db011a64a3b1a3370ab1c3340f48f483e025b6b7fc2bc3113e19471829d3

fix(notice): fix incorrect mention parsing on article publication

---

src/connectors/__test__/commentService.test.ts
src/connectors/commentService.ts

resolve https://github.com/thematters/matters-server/issues/3951

feat(comment): update `countByArticle` & `findByParent` to include correct state comments

---

src/connectors/userService.ts
src/mutations/user/refreshIPNSFeed.ts

resolves thematters/lambda-handlers#125

feat(stop-ipns): stop create IPNS for users without wallet

---

package-lock.json
src/common/environment.ts
src/connectors/cache/index.ts
src/connectors/exchangeRate/index.ts
src/definitions/index.d.ts
src/routes/connections.ts
src/routes/graphql.ts
src/routes/oauth/strategies.ts
src/routes/pay/likecoin.ts
src/routes/pay/stripe/connect/account.ts

resolve https://github.com/thematters/developer-resource/issues/377

feat(caching): support connect to redis cluster

---

src/queries/draft/article/drafts.ts
src/queries/draft/article/newestPublishedDraft.ts

Reverts thematters/matters-server#3909

Revert "feat(draft): temporarily use article version as draft in article drafts API"

---

db/migrations/20240130120100_alter_article_and_draft_drop_fields.js

Reverts thematters/matters-server#3931

Revert "Revert "feat: remove unused columns from article and draft table""

---

src/connectors/articleService.ts
src/queries/article/contents/html.ts
src/queries/article/language.ts
src/queries/article/summary.ts

This reverts commit a5949ce69ae41f60e0cca59de4510b02f0a5500f.

Revert "fix(migration): read old data when no new schema data"

---

src/mutations/user/walletLogin.ts

Now front-end calls `addWalletLogin` to link wallet , link-wallet logic in `walletLogin`  is useless and harmful

feat(wallet-login): remove link-wallet logic in `walletLogin` resolver

---

db/migrations/20240606114312_alter_article_recommend_setting.js
db/sql/create-table-search-index-article.sql
schema.graphql
src/connectors/__test__/articleService.test.ts
src/connectors/articleService.ts
src/definitions/article.d.ts
src/definitions/schema.d.ts
src/mutations/article/toggleArticleRecommend.ts
src/queries/article/index.ts
src/queries/article/oss.ts
src/types/article.ts

feat(search): exclude restricted articles from search result

---

src/mutations/article/editArticle.ts
src/types/__test__/1/editArticle.test.ts

fix(archive-article): invalidate author cache

---

db/migrations/20240612155317_update_user_reader_materialized_view.js
src/connectors/__test__/userService.test.ts
src/connectors/__test__/utils.ts

fix(user_reader): exclude archived articles when calculating authorScore

---

src/mutations/system/putRestrictedUsers.ts
src/mutations/user/updateUserState.ts

fix(put-restricted-users): invalidate related cache

---

package-lock.json
package.json
src/mutations/comment/putComment.ts

ref: https://github.com/thematters/matters-editor/pull/491
resolve: https://github.com/thematters/matters-editor/issues/489

feat(editor): truncate long link text on put comment

---

package-lock.json
package.json

resolve: https://github.com/thematters/matters-editor/issues/497

feat(article): remove <code> supports

---

src/mutations/comment/voteComment.ts

Reverts thematters/matters-server#4017

Revert "feat(notice): remove comment-liked notice trigger temporarily"

---

codegen.json
db/migrations/20240701204319_migrate_notice_detail_type.js
db/seeds/14_notice.js
schema.graphql
src/common/enums/notification.ts
src/common/utils/__test__/mention.test.ts
src/common/utils/index.ts
src/common/utils/mention.ts
src/common/utils/nanoid.ts
src/connectors/__test__/notificationService.test.ts
src/connectors/articleService.ts
src/connectors/momentService.ts
src/connectors/notificationService/index.ts
src/connectors/notificationService/notice.ts
src/connectors/paymentService.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/connectors/userService.ts
src/definitions/notification.d.ts
src/definitions/schema.d.ts
src/mutations/comment/putComment.ts
src/mutations/comment/voteComment.ts
src/mutations/moment/likeMoment.ts
src/queries/notice/index.ts
src/types/__test__/2/notice.test.ts
src/types/notice.ts

- correct `NotificationParams` type
- add moment related notices
- refactor mention extraction logic

feat(moment): add moment related notices

---

package-lock.json
package.json
src/connectors/momentService.ts
src/mutations/campaign/putWritingChallenge.ts

resolve https://github.com/thematters/matters-editor/issues/500

feat(campaign): normalize campaign description

---

schema.graphql
src/connectors/__test__/momentService.test.ts
src/connectors/momentService.ts
src/definitions/schema.d.ts
src/mutations/moment/deleteMoment.ts
src/queries/system/report.ts
src/types/__test__/2/moment.test.ts
src/types/__test__/2/system.test.ts
src/types/moment.ts
src/types/system.ts

- align with `deleteComment` which returns `Comment` , make `deleteMoment` return object too
- allow users to post empty content moments
- fix caching
- fix report moment
- allow users to like their moments

feat(moment): update 

---

schema.graphql
src/connectors/__test__/campaignService.test.ts
src/connectors/campaignService.ts
src/definitions/schema.d.ts
src/mutations/campaign/putWritingChallenge.ts
src/queries/campaign/index.ts
src/queries/campaign/participants.ts
src/queries/user/campaigns.ts
src/types/__test__/2/campaign.test.ts
src/types/campaign.ts
src/types/system.ts

- add `campaign` into `EntityType`
- [add empty write chanllege creation](https://github.com/thematters/matters-server/commit/472b60eea5f2ab8106868361472dd0ad9c654084)
- [allow admin to query all state participants](https://github.com/thematters/matters-server/commit/18acb5d9e479dbe9144bcf82aa59111be8002f78)

feat(campagin): api update

---

src/common/enums/notification.ts
src/connectors/campaignService.ts
src/definitions/notification.d.ts
src/mutations/user/toggleUsersBadge.ts

related PR: https://github.com/thematters/lambda-handlers/pull/145

feat(campaign): add notices

---

db/initDatabase.js
db/migrations/20240717172004_create_action_collection.js
schema.graphql
src/connectors/__test__/collectionService.test.ts
src/connectors/__test__/momentService.test.ts
src/connectors/__test__/utils.ts
src/connectors/articleService.ts
src/connectors/baseService.ts
src/connectors/collectionService.ts
src/connectors/momentService.ts
src/connectors/paymentService.ts
src/connectors/systemService.ts
src/connectors/userService.ts
src/definitions/action.d.ts
src/definitions/index.d.ts
src/definitions/schema.d.ts
src/mutations/collection/index.ts
src/mutations/collection/likeCollection.ts
src/queries/user/collection/index.ts
src/types/__test__/1/collection.test.ts
src/types/__test__/2/campaign.test.ts
src/types/collection.ts
src/types/moment.ts

- add new APIs
- fix codes to avoid [db connection acquiring deadlocks ](https://github.com/Vincit/objection.js/issues/1137#issuecomment-561149456)

feat(collection): add like/unlike APIs and fix db codes

---

db/migrations/20240718201942_alter_article_hottest.js
src/connectors/__test__/utils.ts
src/connectors/articleService.ts
src/definitions/article.d.ts
src/definitions/index.d.ts
src/types/__test__/2/recommendation.test.ts

feat(article-hottest): lower HKD/USDT donation threshold contributed to article hottest score

---

src/connectors/__test__/campaignService.test.ts
src/connectors/campaignService.ts

fix 2024-07-2-prod#PR-2407-2-11

fix(campaign): exclude inactive articles from campaign articles feed

---

codegen.json
schema.graphql
src/common/enums/notification.ts
src/definitions/notification.d.ts
src/definitions/schema.d.ts
src/mutations/collection/likeCollection.ts
src/queries/notice/index.ts
src/types/collection.ts

related PR:　https://github.com/thematters/lambda-handlers/pull/148

feat(collection): add collection liked notice

---

src/connectors/__test__/campaignService.test.ts
src/connectors/atomService.ts
src/connectors/campaignService.ts
src/connectors/notificationService/index.ts

and update find-grand-slam-users sql according latest requirement

feat(campaign): update  `campaign_user.updated_at` and add logging for notification aws API calls

---

src/mutations/campaign/updateCampaignApplicationState.ts

fix(campaign): fix to send notice when approving application using API

---

src/queries/user/recommendation/following/sql.ts
src/types/__test__/2/recommendation.test.ts

product doc: https://www.notion.so/matterslab/c6ca5f412c214c908a81693ea4253789
resolve #4069

feat(recommendation): update user recommendation logic in following page

---

src/common/enums/cache.ts
src/connectors/momentService.ts
src/connectors/notificationService/index.ts
src/definitions/notification.d.ts
src/mutations/collection/likeCollection.ts
src/mutations/comment/deleteComment.ts
src/mutations/comment/putComment.ts
src/mutations/comment/unvoteComment.ts
src/mutations/comment/voteComment.ts
src/mutations/moment/deleteMoment.ts
src/mutations/moment/likeMoment.ts
src/mutations/user/toggleFollowUser.ts

related PR: https://github.com/thematters/lambda-handlers/pull/151

feat(notice): allow to cancel delayed notices

---

src/connectors/notificationService/index.ts
src/connectors/queue/publication.ts
src/connectors/queue/revision.ts
src/definitions/index.d.ts
src/definitions/notification.d.ts
src/mutations/article/editArticle.ts
src/mutations/collection/likeCollection.ts
src/mutations/comment/deleteComment.ts
src/mutations/comment/putComment.ts
src/mutations/comment/unvoteComment.ts
src/mutations/moment/deleteMoment.ts
src/mutations/moment/likeMoment.ts
src/mutations/user/toggleFollowUser.ts
src/types/__test__/2/comment.test.ts
src/types/__test__/utils.ts

- check parent comment state before sending `comment_new_reply` notices
- add sent notices withdraw logic
- refactor both tests and notice withdraw code

feat(notice): add sent notices withdraw logic and refactor

---

db/migrations/20240801112236_alter_article_translation_article_id_index.js

for query in src/queries/article/availableTranslations.ts

perf(translation): add db index

---

db/migrations/20240801112236_alter_article_translation_article_id_index.js

fix db load brought by query in src/queries/article/availableTranslations.ts

[hotfix-master] perf(translation): add db index

---

src/common/enums/notification.ts
src/connectors/__test__/campaignService.test.ts
src/connectors/campaignService.ts
src/definitions/notification.d.ts

related PR: https://github.com/thematters/lambda-handlers/pull/153

feat(campaign): add late bird notice

---

src/connectors/notificationService/index.ts

related PR https://github.com/thematters/lambda-handlers/pull/157
fix PR-2408-19

feat(notice): check lock existence before withdraw

---

src/queries/user/recommendation/following/sql.ts
src/types/__test__/2/recommendation.test.ts

fix(following): exclude archived moments

---

src/common/enums/payment.ts

related: https://github.com/thematters/matters-server/commit/995f0cbae85b06a1bb8ef9a50ec99cdb373c8f23

fix(transaction): add back polygon mumbai to `BLOCKCHAIN_CHAINNAME` to allow resolve mumbai txs

---

src/common/utils/knex.ts
src/queries/user/recommendation/following/sql.ts
src/types/__test__/2/recommendation.test.ts

fix(following): remove actyNodeN if not a collapsed moment

---

src/connectors/momentService.ts

fix(moment): correct typo in notice tag

---

src/connectors/momentService.ts

ref: 
- PR-2408-2-43
- [Figma](https://www.figma.com/design/0d2OccTXpQVsYtY2fABX4X/%E5%8B%95%E6%85%8B?node-id=4287-20464&m=dev)

feat(moment): allow max 1 hard break and 1 soft break for moment

---

src/common/utils/__test__/mention.test.ts
src/common/utils/mention.ts
src/queries/article/language.ts

This is part of the tasks assigned in #3971, the article content would first be stripped of all mentions before being extracted for the excerpt. This is my first PR and I hope I didn't miss anything.

Strip @mention for article language resolver

---

schema.graphql
src/definitions/schema.d.ts
src/mutations/campaign/index.ts
src/mutations/campaign/sendCampaignAnnouncement.ts
src/types/campaign.ts

ref: https://github.com/thematters/matters-oss/issues/710

feat(campaign): add "sendCampaignAnnouncement" mutation

---

schema.graphql
src/definitions/schema.d.ts
src/queries/campaign/articles.ts
src/types/campaign.ts

ref: https://github.com/thematters/matters-web/issues/4857

feat(campaign): revise "WritingChallenge.articles" and return "featured"

---

schema.graphql
src/connectors/openRouter/index.ts
src/definitions/schema.d.ts
src/types/__test__/1/translation.test.ts
src/types/article.ts

* make Gemini 2.0 Flash as default model and Gemini 2.5 Flash as fallback;
* remove unused models;

feat(translation): revise models
